### ISSUE TITLE
How best to deal with missing low level lib?

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo#119]
This seems related to https://github.com/pangeo-data/pangeo/issues/67, but seemed like a new ticket would be best.

I built a custom environment to run some gridding software (pygridgen), but got an error when I imported the package: 
```
 File "/home/jovyan/my-conda-envs/pygridgen/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 137,in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```
I thought that it was a packaging issue for `pygridgen`, but it turns out that [not supplying low level libraries is intentional](https://github.com/conda-forge/pygridgen-feedstock/issues/10#issuecomment-365983589) for packages that depend on `Qt`.   

I was able to work around the missing library by opening a terminal and typing:
```
sudo apt update
sudo apt install libgl1-mesa-glx
```
but is that the best way?

**Comment by mrocklin** [comment]
There isn't currently a good solution to this.  I suspect also that you'll have to do that same command every time you log in after some delay (whenever your container gets shut down)

The only current "official" way is to ask me to add that library into the standard image that everyone uses.

Eventually we would like to make it so that you can build your own image and select that image from a dropdown menu when you (or anyone else on your team) logs in.  See https://github.com/pangeo-data/pangeo/issues/109
