### ISSUE TITLE
Different notebook and worker parent images

### ISSUE THREAD

**Issue by tjcrone** [pangeo-data/pangeo#125]
I noticed that the default notebook and worker images have different parent images, jupyter/base-notebook and continuumio/miniconda3:4.3.14 respectively. These images have a pretty similar kernel, but they are based on different distros from different eras, ubuntu xenial vs debian jesse. They have a very different package profile with lots of different package versions. They also have a fair number of differences in terms of python package versions. Is this being done for a reason? I wonder if it might make sense for the notebook and worker to be more similar, perhaps built from the same parent?

**Comment by mrocklin** [comment]
That would be welcome.  Things were done this way in order to avoid having
to recreate the entire base-notebook stack so that we knew the notebook
image was JupyterHub compliant (their dockerfile is non-trivial).  One
could also create a new miniconda image based on the different linux distro
if this was critical.

The python packages should be roughly the same though (although one uses a
named environment).  My hope is that this is enough to cover most cases.
If you're running into other issues though you might want to check out the
Dockerfiles in gce/{notebook,worker}

**Comment by tjcrone** [comment]
A package that I need for my work, PyAV, needs to be built from source (using Cython). It builds on the notebook with some coaxing, but will not build on the worker. Once we get our own Pangeo up and I have more control over what images we run, this issue should be solved for me. But I thought others may end up having similar issues with these images.

**Comment by mrocklin** [comment]
Alternatively you can specify your own docker image in the
worker-template.yaml file .  If you are familiar with Docker this would let
you customize things how you like locally and then upload that environment
for use everywhere.

**Comment by tjcrone** [comment]
Oh that's a totally workable solution. Thanks!
