### ISSUE TITLE
Singularity?

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo#159]
Our IT folks are promoting Singularity (http://singularity.lbl.gov/) over Docker for our local HPC facility. 

They pointed me toward to this [NextPlatform article](https://www.nextplatform.com/2017/04/10/singularity-containers-hpc-reproducibility-mobility/) which states:

> Unlike Docker (currently the most well-known enterprise container system) and other container systems, Singularity preserves the security of the host HPC system and does not represent a breach of security. Plus Singularity includes MPI – an essential part of HPC computing.
> 
> Succinctly, if a user wants to be root inside a Singularity container, they must first be root on the system outside the container. A user with root access can view and change any file on the system – either inadvertently or maliciously. Thus, HPC security models tightly control root access and forbid non-authorized people (e.g. general users) from gaining root access. Due to the design of Docker and other enterprise container systems that utilize root-level user-writable daemons and other security-permeable design features, HPC systems managers have to isolate the both HPC networks and user access to data before these containers can be allowed on the system.
> 
> The ramifications are far-reaching and precludes access to InfiniBand and Intel OPA high performance and optimized storage platforms as well as locally mounted file-systems."

Has anyone looked at this for Cheyenne or other HPC and have thoughts?   

Just curious whether I should look into this more or not...

**Comment by kmpaul** [comment]
@rsignell-usgs Yes, we've looked into Singularity, but I think it's been a while.  I, personally, did not look at it, but there was a presentation on some of our internal testing of containers in December of last year.

At the time that we tested Singularity, there were some "security issues" for which the Singularity developers did not have good solutions.  I don't know what those "security issues" were, but I was told that the Singularity developers devised solutions that resulting in limiting critical functionality of Singularity.  ...Again, though, I don't know what "critical functionality" was limited, or what the solution actually was.

On Cheyenne, we do not use either Docker (for the reasons you quote above) or Singularity (for the reasons that I quoted above).  We are currently using our own version of containers, called Inception (https://github.com/NCAR/Inception).  And for more details, I might direct you to the Github repo for Inception, and to the developers, @nateucar and @matthewsucar.

**Comment by rsignell-usgs** [comment]
Thanks @kmpaul.  Very useful!

**Comment by kmpaul** [comment]
You are very welcome, @rsignell-usgs!   I'd be interested to hear what solutions you find and/or investigate.  One enormous (and obvious) advantage of Singularity over Inception is the size of the development community.  If Singularity works for you, I think we might be interested in reinvestigating our solution so that our folks don't have the support burden.

**Comment by jreadey** [comment]
Does Singularity and Inception work transparently with Kubernetes?   If Kubernetes is doing the container management I'm a bit confused as to what the essential difference between Singularity/Inception/Docker are.

**Comment by jacobtomlinson** [comment]
We are also actively investigating Singularity.

My short explanation of a comparison with docker is that Singularity is a very pragmatic style of containment. I would say that it "contains less" (no network containment, no user containment, etc) but that also makes things much simpler for many applications. For example MPI is a nightmare in the docker virtual network, singularity doesn't have that problem because it just uses the HPC's network with no abstraction. Also user management is simpler because you are the same user in the container as you are on the host system, this makes security and auditing simpler.

Of course there are many reasons why strong containment is provided by docker but I feel these are more useful in a micro services style scalable application deployment, in an HPC environment a weaker containment is preferable.

**Comment by kmpaul** [comment]
@jacobtomlinson Thanks for the explanation.  

I might add that another different (that I am actually aware of) is that Singularity and Inception are designed to work with "traditional" HPC job schedulers, like slurm, rather than Kubernetes.  If Singularity and/or Inception can work with Kubernetes, then it's news to me.

**Comment by guillaumeeb** [comment]
We're also experimenting with Singularity at CNES. Docker is a nightmare for HPC environments, we're struggling to allow its use on our platform, currently we have developed a wrapper that limits the potential usage of Docker (eg. gaining root access) during execution, but it's rather painful to support and not at all satisfying from my point of view.

Singularity, and its compatibility with Docker images, could provide a welcome alternative. I know of several other places/labs in France where its use is growing. We will hopefully be able to provide more feedback later this year.

It would be great if Singularity was more compatible with Kubernetes or Mesos or other container orchestrator, but I've never heard of that either. To me, Singularity is clearly more batch job oriented than micro-services. So I don't know if it will reduce or widen the gap between HPC and Cloud environments...

At the end, Singularity images are just seen as a packaged binary, that you can run from any mounted filesystem.

**Comment by rsignell-usgs** [comment]
Leaving this open as it seems there is still exploration to be done here...

**Comment by JiaweiZhuang** [comment]
I've been testing Singularity on both AWS EC2 and Harvard's [Odyssey](https://www.rc.fas.harvard.edu/odyssey/) cluster [which just had Singularity installed](https://www.rc.fas.harvard.edu/odyssey-3-the-next-generation/). I believe Singularity is targeted at **model simulations (tightly-coupled MPI programs)** while the Kubernetes+dask+xarray ecosystem adopted by Pangeo is focused on distributed **data processing** (almost embarrassingly parallel; no need of point-to-point communication like MPI). Thus they have very different use cases and are not quite comparable.

There are some discussions on using Kubernetes for HPC applications ([k8s blog](http://blog.kubernetes.io/2017/08/kubernetes-meets-high-performance.html)), but I've never seen any real use cases. On the other hand, Singularity is being adopted quickly in the HPC world. If you want to run **HPC programs** on the cloud then Singularity might help. 

For **data processing**, I don't think Singularity has real advantages over Docker&k8s. The only "advantage" I can think of is Singularity feels much more intuitive than Docker&k8s for domain scientists who know little about IT/web. 

For reference, I am working on enabling our GEOS-Chem model on AWS. Our [docs](http://cloud-gc.readthedocs.io) has [one chapter on Singularity](http://cloud-gc.readthedocs.io/en/latest/chapter03_advanced-tutorial/container.html). It integrates well with [HPC environment on AWS](http://cloud-gc.readthedocs.io/en/latest/chapter03_advanced-tutorial/hpc-overview.html).

**Comment by mkjpryor-stfc** [comment]
As far as I am aware, @jacobtomlinson is pretty much correct. Although Kubernetes and Singularity both use Docker images, they solve different problems.

When integrating with an existing bare-metal batch system, Singularity simplifies things a lot by utilising the host network and UID/GID space. When running a microservice architecture in Kubernetes, you want control over these things in your containers, so Singularity is not so appropriate.

**Comment by mkjpryor-stfc** [comment]
@JiaweiZhuang: For something like Pangeo, the Docker + Kubernetes combination really comes into its own when it is not directly exposed to the users. The users interact with JuptyerHub, Notebooks and Dask, and the fact it scales up and down on a Kubernetes cluster underneath is not really their concern.

**Comment by JiaweiZhuang** [comment]
> For something like Pangeo, the Docker + Kubernetes combination really comes into its own when it is not directly exposed to the users.

You are definitely right -- as long as users don't manage JuptyerHub on their own, they don't need extra software skills. I am just a bit curious about Pangeo's business model. Is it going to provide computational resources for everyone for free? I can imagine some users might need big computing power that cannot be afforded by Pangeo's budget. If they want to deploy clusters under their own Google/AWS account, they need extra software skills. For people from the science world, Docker&k8s (mainly designed for web apps) have a much steeper learning curve than Singularity (mainly designed for HPC). Indeed, this would be a non-issue if the instruction is clear enough.

**Comment by rabernat** [comment]
> I am just a bit curious about Pangeo's business model. Is it going to provide computational resources for everyone for free?

During the 3-year NSF project, we are happy to allow people to access pangeo.pydata.org and use it as much as they wish. Having more demand than we can afford would be a great problem to have! We are very far from that point now, since we have not publicized the resource heavily (and it is still a bit buggy).

> If they want to deploy clusters under their own Google/AWS account, they need extra software skills.

We are definitely also interested in empowering people to deploy their own pangeo environments on their own computing resources. It sounds like Singularity could be valuable for this purpose in certain environments.
