### ISSUE TITLE
Autoscaling on Azure

### ISSUE THREAD

**Issue by tjcrone** [pangeo-data/pangeo#185]
Key to a cloud-deployed Pangeo system is it's ability to work with an underlying Kubernetes cluster that can autoscale, creating new nodes in the cluster to accommodate new worker pods as needed. However, it appears that Azure AKS may not have autoscaling node pools out of the box. It looks like this capability might be enabled with some [secondary](https://medium.com/@wbuchwalter/autoscaling-a-kubernetes-cluster-created-with-acs-engine-on-azure-5e24ddc6402e) [packages](https://github.com/kubernetes/charts/tree/master/stable/acs-engine-autoscaler), but I'm having trouble getting it working. Has anyone figured out how to get Azure node pools to autoscale? Are there built-in settings that I am missing? Or can anyone provide some pointers on how to get these external packages working? Some of the settings for the autoscaler config are easy to establish, but some of them are not. Any advice on this issue would be greatly appreciated!

**Comment by jacobtomlinson** [comment]
We use [cluster autoscaler](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) on AWS for scaling our [kops](https://github.com/kubernetes/kops) cluster.

Looks like it supports Azure too.

**Comment by tjcrone** [comment]
Thanks @jacobtomlinson! Looks like this autoscaler supports some types of Azure clusters, but [not AKS](https://github.com/kubernetes/autoscaler/issues/753) quite yet. It's clearly on the todo list. Has anyone else looked into this? Maybe looked into running Pangeo on another type of Azure cluster that is supported (i.e. VMSS and VMAS)? kops looks awesome btw.

**Comment by mrocklin** [comment]
Do you have a contact within Azure?  Have you tried reaching out to them?

**Comment by tjcrone** [comment]
Not yet. Would you suggest that I reach out to one of the people in the email you recently sent to Ryan and me? Or is there another more k8s focused person that might be appropriate?

**Comment by mrocklin** [comment]
No, I would not reach out to those people, they do ML things.  If you have
some allocation with Azure then its likely that they also connected you to
a support engineer.  You would want to contact that person.

**Comment by feiskyer** [comment]
Azure support in cluster-autoscaler has been added from v1.2.0. See documentation [here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/README.md).

If you have any problems, please let me know

**Comment by tjcrone** [comment]
Thanks @feiskyer. Does this autoscaler work for AKS? Or just ACS-engine?

**Comment by tjcrone** [comment]
A MS support engineer directed me [here](https://docs.microsoft.com/en-us/azure/aks/tutorial-kubernetes-scale), which suggests that an AKS cluster can autoscale in response to CPU load, not in response to unschedulable pods. Does anyone have any thoughts on how this would work with Pangeo?

**Comment by mrocklin** [comment]
I suspect that by "cpu utilization" they actually mean "the amount that a
pod says it will use" not the actual metrics within the process.  I suspect
that this will happily scale with our current setup.

**Comment by tjcrone** [comment]
Thanks @mrocklin. I will give it a shot. However reading the autoscaling section of that page more closely, it seems to suggest that this can increase the number of pods in a "deployment", whatever that means, rather than scale the number of nodes in a cluster. I'm not sure I understand what this particular autoscaler does.

**Comment by mrocklin** [comment]
Ah, perhaps you're right.  In that case I would go back to the Azure
engineer and mention that you're specifically interested in autoscaling
nodes, not pods.

**Comment by feiskyer** [comment]
> Thanks @feiskyer. Does this autoscaler work for AKS? Or just ACS-engine?

Only VMAS with acs-engine or VMSS (with any deploy tools) are supported yet. We are working on AKS support now

**Comment by jpoon** [comment]
In the meantime, could you use something like `acs-engine` to deploy your Kubernetes cluster to Azure? With `acs-engine` there is support for https://github.com/wbuchwalter/Kubernetes-acs-engine-autoscaler.

**Comment by DPeterK** [comment]
As per my comment in #82, I'm aware that this is an old, stale issue. However, as I'm working on getting a Pangeo deployment working on Azure, I have explored the space of autoscaling on Azure AKS clusters.

Since this issue was raised I think the Azure offering has moved on some. Now there are a few ways to produce scaling AKS clusters:
* [virtual nodes](https://docs.microsoft.com/en-gb/azure/aks/virtual-nodes-cli) / [virtual kubelet](https://docs.microsoft.com/en-gb/azure/aks/virtual-kubelet)
* [cluster autoscaler](https://docs.microsoft.com/en-gb/azure/aks/cluster-autoscaler)
* it's a slight tangent, but there's also the option to use [multiple node pools](https://docs.microsoft.com/en-gb/azure/aks/use-multiple-node-pools)

We've successfully used both **virtual nodes** and the **cluster autoscaler** to create an autoscaling cluster, using [dask-kubernetes](https://github.com/dask/dask-kubernetes), in a WIP Pangeo deployment on Azure. It's worth noting that both of the technologies we've trialled are still preview technologies on Azure, with some associated issues. We're communicating with Microsoft about these, though, so we'll hopefully continue to see improvements to these technologies.

**Comment by yuvipanda** [comment]
Awesome, @DPeterK! Going to re open this since autoscaling is pretty important to running on any cloud provider

**Comment by jpoon** [comment]
@DPeterK who have you been working with on the MSFT side? cc @timfpark who could be of service.
