### ISSUE TITLE
organization of example notebook gallery

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#201]
Within the pangeo / xarray milieu, we have a proliferation of gallery / example sites

- xarray
  - [gallery](http://xarray.pydata.org/en/latest/auto_gallery/index.html)
  - [examples](http://xarray.pydata.org/en/latest/examples.html)
- main pangeo repo
  - `notebooks/`
  - `doc/use_cases`
  - `gce/notebook/examples` (gets put into Docker image on pangeo.pydata.org)
- dask
  - [dask gallery](https://github.com/dask/dask-examples)

This is not an ideal situation.

Quoting @fmaussion in #191 
>  one issue is "simply" organizational and can be solved by dedicated refactoring / selection of examples.
> The other issue I see (here and for other computationally expensive projects I'm involved in) is that some examples can't be built on ReadTheDocs, which is awesome but slow and unreliable. Building the docs elsewhere would help to have more expensive examples with the risk of static notebooks which will be difficult to maintain.

What are some ideas for both how to re-organize these and also how to auto-build expensive notebooks?

**Comment by rabernat** [comment]
One idea would be to use pangeo.pydata.org to build the expensive notebooks. If we could find some CI magic to actually spawn a pod within the cluster and build the docs from it (we currently use travis: [travis.yml](https://github.com/pangeo-data/pangeo/blob/master/.travis.yml)), then we could also spawn dask clusters directly from the notebooks. This would be extremely cool.

**Comment by mrocklin** [comment]
Dask examples live here: https://github.com/dask/dask-examples

**Comment by mrocklin** [comment]
> One idea would be to use pangeo.pydata.org to build the expensive notebooks

I'm against this.  These examples are likely to outlive our deployment here.  We're also not stable enough to form this level of infrastructure.

Instead, I suspect that people usually use travis-ci or circle-ci.  For *very large* examples I suggest that we just discourage them or else run them statically and don't test them.

**Comment by rabernat** [comment]
I see you point. So that suggests examples will fall into two categories:

- Notebooks cheap enough to run on travis and built dynamically
- Notebooks run elsewhere and displayed statically

**Comment by jbednar** [comment]
FYI, my group's sites [Datashader.org](http://datashader.org) , [HoloViews.org](http://holoviews.org), [PyViz.org](http://pyviz.org), and [EarthSim](https://pyviz.github.io/EarthSim) follow roughly the pattern that Matt is describing, using Travis CI to build all the notebooks that are practical to build in the CI system.  There are other notebooks (e.g. the [Datashader Topics](http://datashader.org/topics)) that require data files too big to be fetching during a Travis build, and for those we use the same machinery on a local machine (still automated, but only spawned explicitly) and publish the results.  There's one additional wrinkle, which is that even for the huge datasets we make a tiny subset available for the regular CI builds so that the basic process of running the notebook *is* tested and repeatable; it's only the large-data aspects that are done manually.  We are in the process of making all of this infrastructure available as the [NBSite](https://pyviz.github.io/nbsite) and [PyCT](https://github.com/pyviz/pyct) projects that automate the process of turning notebooks into automatically built, tested, and deployed websites.  If you're interested, the projects are still a bit rough (especially in visual appearance!), but are rapidly settling down to provide support for the types of work described above.

**Comment by jbednar** [comment]
As it happens, we need that too. :-) Adding in an easy way to deploy a notebook into a runnable binder-based copy is already on our list, but that's a goal we've put aside for the time being to focus on making the overall workflow for turning the crank from notebooks to deployed  (static) site be more polished and more straightforward.  As soon as that's done, it's back to working on putting in the "Try me out on Binder" button.

NBSite is already fully functional and is in use for building EarthSim and PyViz.org, but we have about a dozen other projects using various older versions of it, and we are currently focusing on cleaning up a few rough bits and then deploying it uniformly across all our projects so that we can have only one single package to maintain.  This coming week we'll all be putting on a conference, but this is something we'll get back to as soon as we get back and should expect to be deploying over the following week. So it's available already, but if you can hold off a couple of weeks we'll have it much more in a state ready to copy and spread.

**Comment by jbednar** [comment]
BTW, NBSite focuses on making it easy to maintain a Python package supported by notebooks, but our original interest in making HoloViews work well with notebooks came from trying to ensure that our research was reproducible, for which we've published a [manifesto](http://conference.scipy.org/proceedings/scipy2015/pdfs/jean-luc_stevens.pdf).  That paper predates some of the tools now available, but I think that the combination of:

- HoloViews to make notebooks be readable while containing the full, domain-specific details needed to reproduce results, with
- Conda to capture the environment needed to run the notebooks, and 
- NBSite to be able to build and deploy notebooks in an automated way as part of a website, and
- NBVal to verify that the results from the notebooks match the originally specified results, and
- MyBinder to allow notebooks to be run with a live Python-backed  server so that people can easily dive right into the work in the notebook

is a pretty compelling way to capture what's been achieved, archive it, and then launch people off to build on the work.  If only all my students had had this when finishing up all their projects, so other people could pick up precisely where they left off!

**Comment by tjcrone** [comment]
https://www.theatlantic.com/science/archive/2018/04/the-scientific-paper-is-obsolete/556676/

c/o @friedrichknuth

**Comment by kmpaul** [comment]
Anybody thought about using https://github.com/nbgallery/nbgallery?  I've heard some people say nice things about it and its extensions, https://github.com/nbgallery/nbgallery-extensions, which can integrate it with JupyterHub.

**Comment by rabernat** [comment]
Do we know if it is possible to use nbgallery but *not rebuild* the notebooks. As discussed above, some use case notebooks will be very expensive computationally and not practical to auto-build. It sounds like nbgallery is really designed as a notebook build environment.

**Comment by kmpaul** [comment]
@rabernat Yeah.  I'm not sure.  I've just heard some people "rave" about nbgallery, but I think you are correct; It provides an environment that executes the notebooks.  I will downgrade my own response.
:-

**Comment by Chilipp** [comment]
Concerning the issue about expensive notebooks on RTD, I also developed a sphinx extension named [sphinx-nbexamples](http://sphinx-nbexamples.readthedocs.io/en/dev/) that works the same as [sphinx-gallery](http://sphinx-gallery.readthedocs.org/en/latest/) but renders jupyter notebooks instead of python scripts by using nbconvert. 

Therefore you can select in the sphinx `conf.py`, whether you want to execute the notebook or not (see [the docs](http://sphinx-nbexamples.readthedocs.io/en/dev/getting_started.html#preprocessing-the-examples-or-not)), e.g. via

```python
example_gallery_config = dict(
    dont_preprocess=['../examples/expensive_notebook.ipynb'],
    )
```

I use that in my [psyplot project](http://psyplot.readthedocs.io/en/latest/examples/index.html) and you can also [link to other documentations](http://psyplot.readthedocs.io/en/latest/index.html#examples) to include their examples as well.

**Comment by rabernat** [comment]
@Chilipp I just looked into sphinx-nbexamples. It looks perfect for the pangeo website.

If you would like to try to refactor our use case gallery to use sphinx-nbexamples, that would be extremely appreciated. PR welcome!

**Comment by Chilipp** [comment]
Sure @rabernat! I'll keep you posted

**Comment by jhamman** [comment]
+1 for sphinx-nbexamples. I have been working on setting up a pangeo binder server (#283) which would allow us to launch our notebook examples directly from our documentation site.
