### ISSUE TITLE
JupyterHub server for Cheyenne

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#26]
To reduce startup costs it would be convenient to set up a JupyterHub server that would launch notebooks with easy access to Cheyenne.  We might then make a small Python package that would launch Dask workers on PBS from a local notebook.

**Comment by jhamman** [comment]
@mrocklin - Either @davidedelvento or @kmpaul were saying there is something in the works on this front. Hopefully they can keep this issue updated as things evolve on the NCAR/CISL side.

**Comment by davidedelvento** [comment]
I am working on this. It is not something that will happen tomorrow, but it will take several weeks if not months. Do you care about the nitty gritty development details? I'll be happy to provide them if you care.

**Comment by mrocklin** [comment]
It might be useful to state your approach on some public forum like this so that we can ping JupyterHub devs to check in and help provide feedback.

I'm personally interested in a few things, like access from outside networks and the availability of ports for Dask's diagnostic web pages.

**Comment by davidedelvento** [comment]
The full story is too long. I'll give you the summary of the summary, which I deem enough

Probably known by most reading this, but just to make sure, let me start from the basics. The big picture of jupyter is that jupyterhub is the "outside shell", supporting multiple users, which then starts jupyter notebooks (owned by individual users), which in turn starts jupyter kernels, which can be in different programming languages (e.g. python or R).

Jupyter notebook (note I did not say "Hub") are already supported in Cheyenne as described here:
https://www2.cisl.ucar.edu/resources/computational-systems/cheyenne/software/jupyter-and-ipython
As you can see, the "getting started" setup is quite clunky. I am not sure if any kernel other than python is installed on Cheyenne yet, but if not it'd be a quick enough thing to do.

@kmpaul  and I want to streamline the process and make it possible to have it work in the "classic" form of web service, namely just go to a web address, login in and work in your browser, instead of that complicated and double-login setup described in the docs above. To make that happen there are several approaches, but the one that seems more likely to be accepted in NCAR environment (for security and other policies) is the one in which just the jupyterhub (notice now I DID say "hub") front-end is running on a VM managed by the web group, at an address such as jupyterhub.ucar.edu or the like. A common setting of the hub is to have the jupyter notebook start on the same machine where the hub is running. However this is not feasible at NCAR because:

* the HPC platform (Cheyenne) will never be exposed as a web resource, and therefore the hub cannot be run there (well it might be run by jumping through several hoops, but it will never be visible
from outside without a clunky ssh tunnel) 
* the web platform (e.g. what I called jupyterhub.ucar.edu) can easily be a wimpy VM where running just the hub is easy, but running the notebook would be hard. 

So the best approach would be to have the notebook run on cheyenne while the hub is running on the front-end (another option would be for just the kernel to run on cheyenne, and that would change some of the details without having us to gain much -- and require a beefier web platform with much more complicated authentication system). Both things are technically possible, in fact some similar
"nuts-and-bolts" to make it happen already exist. For example there are some based on DockerSpawner or KubeSpawner. Unfortunately, on Cheyenne we can't use Docker or Kubernete, and certainly not control them from "the outside" (i.e. the hub). We need a fully-fledged sshSpawner. On top of that, we need to submit a PBS job, and here is where batchspawner could help, but not on its own, since it's missing the ssh step before. See https://github.com/jupyterhub/batchspawner
for details on this project. Even splitting the frontend-backend at that other boundary (i.e. kernel instead of notebook) will not change much this discussion, see for example https://github.com/korniichuk/rk/issues/16

So we need to implement these missing pieces, one way or another. The biggest roadblock in this regard if the issue described at https://github.com/ipython/ipython/issues/514 which we need to find a
good workaround for. In a sentence, the problem is that running ssh in python is easy, however ssh strongly needs the password to be typed directly into it and not "passed-by" something else such as a python program running in a web browser. Once we have this roadblock removed, the rest is just "putting pieces of the puzzle together" which may require some time, but not huge effort.

Hope this is clear enough and the right level of details.

**Comment by willirath** [comment]
At Geomar, we're running a jupyterhub launching Jupyter on the hub and then connecting to (virtually all of our) HPC machines via https://pypi.python.org/pypi/remote_ikernel

While we're using SSH-key auth only, the docs state that the package aims at supporting password input as well.

**Comment by mrocklin** [comment]
@davidedelvento how are things going on this?  Also, have you reached out to any of the Jupyter devs about this?  I know that a number of other HPC facilities have done something similar.  cc'ing @minrk in case he can route us to the proper contacts.

**Comment by mrocklin** [comment]
@minrk can you point us to groups that manage HPC systems that provide JupyterHub frontends?  Are there groups at NERSC or SDSC that have been successful here and might have systems that we can copy?

**Comment by minrk** [comment]
@zonca at SDSC, @mbmilligan at UMN, and @shreddd at NERSC each have a version of JupyterHub on HPC.

**Comment by zonca** [comment]
@mrocklin @minrk see here for all my configuration files:

https://github.com/jupyterhub/jupyterhub-deploy-hpc/tree/master/batchspawner-xsedeoauth-sshtunnel-sdsccomet

It is basically:

* https://github.com/jupyterhub/batchspawner with custom form for choosing job options
* oauthenticator with XSEDE CILogon
* SSH tunnel back from the computing node to the JupyterHub server with user that has no shell

**Comment by davidedelvento** [comment]
@mrocklin I have not made much progress on this on Cheyenne, and I was already collaborating with Andrea (Zonca). 

It is in my todo list for this week, and I found a way around the password issue that I mentioned above (but I haven't tested it yet).

**Comment by jhamman** [comment]
@davidedelvento - Can you provide an update on what you've been up to here? In our NCAR call this morning, you articulated some issues that would be good to document here. It is possible that @yuvipanda or others may be able to point us in a different, more productive direction.

**Comment by davidedelvento** [comment]
My summary above is still accurate. What is missing is that I studied and installed https://github.com/cfriedline/remote_ikernel on the "wimpy frontend". Remote_ikernel is the only solution which already support passwords without me having to implement that part of the functionality. 

What happened is that the minimum mistake I make (and of course I make many while building the system and exploring different configuration settings), this set of events happen:

- the kernel freezes on the server (not too bad, I can kill it)
- the browser I am using freezes totally (very bad) even in a one-process-per-tab browser like chrome everything stops (horrible)
- the browser itself becomes unkillable (at least on Linux, which is the only desktop I have available for testing at the moment) regardless of the signal sent, even with SIGKILL (i.e. 9). Now, before you say "SIGKILL never fails to kill a running process" that is not true for a process stuck in some  ninterruptible state such as kernel call waiting for something low level
- the only way I've found to restore functionality of my laptop is to reboot (puke-level horrible)

Now, I think I can use a VM or something (for faster reboots) and keep developing on this until I've got it right and it works, however, should I succeed and should we deploy this, anything go wrong for a user would basically require a reboot for them (at least on Linux, would you like to volunteer and see if I can break your Windows or Mac browser?)

**Comment by mrocklin** [comment]
I recommend stating your intent and raising these issues on some of the Jupyter community channels, like https://gitter.im/jupyterhub/jupyterhub .  It might also be helpful if you were to fully specify your current approach (are you using JupyterHub?  Are you using BatchSpawner?  If so, with what configuration?  and so on.)

**Comment by davidedelvento** [comment]
@mrocklin Mmmm, I thought my intents and methodologies were clear, but let me restate them here in other words.

* I am using JupyterHub
* JupyterHub must run on a different machine (compared to where Jupyter is running)
* Going from one machine to another requires password-based authentication
* I am not using BatchSpawener but remote_ikernel because my understanding is that the former only support key-based authentications which are a big NO-NO in our case (however I'm open to give it a try and even to make code changes and PR to support what I need, if necessary and not too much work -- I've not done so yet for various reasons one of which is that BatchSpawener's tests are currently failing on master, so that does not feel like the right place/time to start)

**Comment by mrocklin** [comment]
Thanks for the clarification @davidedelvento !

**Comment by davidedelvento** [comment]
@yuvipanda do you have any suggestions on what to explore here? @kmpaul recommended that I ask you

**Comment by jhamman** [comment]
Am I correct in my understanding that the leading question here is what is the best way to spawn kernels on remote machine using a password based authenticator?

**Comment by davidedelvento** [comment]
@jhamman you are more or less correct. However "best" is an overstatement, since there is no known (to me) solution that works at all. I'd either say:

> what is the _least worse_ way to spawn kernels on remote machine using a password based authenticator

or (probably better)

> what is the best way to spawn kernels on remote machine using a key-based authenticator which you believe is easy enough to modify and/or well-written in a way to facilitate contributions and/or likely to accept my PRs so that I can implement the password-based auth myself

**Comment by yuvipanda** [comment]
Heya! Thanks for the ping :) 

@davidedelvento I'm at a loss about your browser freezing experiences. It feels unrelated to JupyterHub as such to me (I've had similar experiences with completely unrelated setups on my linux desktop too).

I think remote_kernel is your best choice, and IIRC it is actively developed. https://github.com/jupyterhub/batchspawner is the other option.

**Comment by jhamman** [comment]
Keeping this open since it sounds like people are moving this forward at NCAR (@kmpaul)!

**Comment by kmpaul** [comment]
Yes!  Definitely.  Your stale-bot moves faster than bureaucracy!

This is making some progress, actually.  @yuvipanda now has a Cheyenne account and ability to do some testing of our system, and he is talking with @davidedelvento about a preliminary Jetstream-based approach.  I think there are some cool possibilities that we are exploring, including a neat new tool that Yuvi found called [udocker](https://github.com/indigo-dc/udocker) for running docker containers in user-space on HPC systems.  Cool!
