### ISSUE TITLE
Shared environments between Dask workers and Jupyter pod

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#272]
Many of the challenges we have today are about how best to update user software environments, support multiple software environments, etc..

On various video calls we have also discussed removing this concern by giving user's more control over their environment, which would offload the burden from core maintainers. 

There are a few challenges to this:

1.  Workers need to have the same software environment as is in the Jupyter Pod.  People have proposed solving this by mounting the user's drive read-only on all of the workers
2.  Users need to install software in user space that won't be destroyed or overwritten when they get a new pod.  Presumably on startup we need to install miniconda in the user's directory, rather than directly within the docker image (which would also have the nice effect of reducing the size of our images)

cc @yuvipanda and @jacobtomlinson about point 1

**Comment by rabernat** [comment]
What if we were able to use the same docker image for both notebook and worker? This would simplify several things. The images are already similar in size. Presumably there would just need to be some environment variable to tell the pod whether to run the notebook startup script or the worker startup script.

**Comment by tjcrone** [comment]
I spent a long while trying to get this going on Azure, because "Azure File", which is SMB, allows [ReadWriteMany](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes) access. I pretty much had it working, but because Azure File is SMB it doesn't do Unix permissions properly, I gave up. And as far as I can tell, it is not possible to easily mount a drive with one pod as read-write, while allowing other pods read-only access. I believe it can likely be done using an NFS volume, but from what I can tell this might be fairly complicated. @yuvipanda is the expert's expert on this, and has many issues/threads discussing the use of NFS persistent volumes. If you want to have the workers share the same home directory as the notebook, I think getting an NFS solution figured out is probably the best route.

I support moving to a system where the notebook and worker use the same image.

**Comment by mrocklin** [comment]
To be clear using the same image only gets us a little bit of the way there.  Their environment will be the same when they first start their first session.  Any change they make will not be covered.  In this issue I'm actually suggesting that, if we can get them to share a file system then we remove the conda environment from the docker image completely.  I want us to get out of the game of determining what versions of software users run.

**Comment by guillaumeeb** [comment]
Is'nt the Docker volume mechanism a good solution for this? 
see https://docs.docker.com/storage/volumes/#share-data-among-machines.

I don't know if there is Google Cloud volume driver though, even if they are talkin about AWS and Azure in the doc.

**Comment by rabernat** [comment]
> We currently use the same image for the notebooks and workers.
> 
> Allowing access to the users home directories from the workers is on our roadmap, however our current volume type can only be mounted on one host so we need to switch to a different type and migrate existing home directories first.

I would like to move forward on this issue. @jacobtomlinson: can you share the Dockerfiles and related scripts which allow you to use a single image for both notebook and worker. Currently we have the following:
- https://github.com/pangeo-data/helm-chart/blob/master/docker-images/notebook/Dockerfile
- https://github.com/pangeo-data/helm-chart/blob/master/docker-images/notebook/prepare.sh
- https://github.com/pangeo-data/helm-chart/blob/master/docker-images/notebook/Dockerfile
- https://github.com/pangeo-data/helm-chart/blob/master/docker-images/notebook/prepare.sh

**Comment by mrocklin** [comment]
I think that our notebook image is based off of jupyter's base-notebook
image

**Comment by jacobtomlinson** [comment]
Yeah looks like it. Ours is based of the scipy one, which I think is based off the base-notebook and adds scipy and some other packages. 

I assumed that all the jupyter images eventually tree up to miniconda, but it turns out the are starting from ubuntu and installing miniconda (which is basically what the miniconda image does anyway).

https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile

Either was I would just add any packages to the notebook image which are in the worker image and then try using the notebook image in place of the worker image. I expect it should *Just Work TM*.

**Comment by jacobtomlinson** [comment]
It will cause the example notebooks to be cloned onto all the workers at run time. But that can be removed later.

**Comment by yuvipanda** [comment]
There are two ways to do this in the long run:

1. Use NFS for home directories. This might be something that PANGEO wants to do anyway, since it offers *massive* cost savings. Then mount your home directories in your worker pods. HPC style.
2. Run a [NFS Ganesha](https://github.com/nfs-ganesha/nfs-ganesha/wiki) sidecar in each user pod. This allows you to share the homedir / other system contents with your workers.

I think (1) is the easier option. AWS has EFS, Google has Cloud Filestore.

**Comment by jhamman** [comment]
For those that come along this issue later, we are currently using the same docker image for workers and jupyter pods BUT they are NOT on a shared file system. Instead, the notebook image just tells dask-kubernetes to use the same image. This solves the problems related to maintaining two docker images but does not solve the problem of user updates to the runtime environment.

**Comment by drorspei** [comment]
A year and a half into the future, how are guys doing it now? Do you have new insight into the runtime environment problem?

**Comment by TomAugspurger** [comment]
I think the user-environment issue is largely unchanged.

For binder, we have a pretty decent setup: There's a draft blogpost on this (background and our solution) at https://docs.google.com/document/d/14m-TNi2R4VaTI0g2vy15LBRGDkur2B21wiAdrTt6nBg/edit?usp=sharing that will be published on the pangeo blog once we find time to finish it off.

**Comment by drorspei** [comment]
That is really helpful, thanks
