### ISSUE TITLE
Pangeo GitHub membership

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#403]
I've been toying around with some ideas related to how we manage Pangeo's membership. I want to get people's thoughts on a few ideas:

Currently, the Pangeo community is loosely defined and membership is spread across a few areas:
- an old pangeo list serve that isn't used much anymore (pangeo@googlegroups.com)
- the pangeo github organization (currently 24 members)
- the pangeo gitter channel (currently 34 members)
- the pangeo.pydata.org login list (roughly 1000 members)
- the pangeo collaborators list (http://pangeo.io/collaborators.html#people)

There is a lot of overlap in these groups but we don't currently have any way to bring them all together. 

I'm going to suggest the idea of using the pangeo-data GitHub organization as the thing that brings them all together. We could:

- automate the process of adding new members from existing lists (website, jhubs, etc)
- use GitHub Teams for communication (e.g. "you all have logged on to pangeo.pydata.org, we'll be shutting that down soon")
- Use GitHub Teams for authentication on federated jupyterhubs

Thoughts?

------

This is also related to #64

**Comment by mrocklin** [comment]
I don't think that we should do anything special for the 1000 people who
have logged in.  I don't think that they should be considered members.
FWIW I suspect that the median user would prefer not to get an e-mail from
us about us removing their drive.  They tried it once and haven't come
back.  Even for those who do use it, we've been pretty diligent about
saying that it's experimental and shouldn't be trusted.

**Comment by jhamman** [comment]
Fair point. We can disregard the list of users on the JupyterHub or come up with a metric that helps describe if a use has been routinely using the platform.

**Comment by jhamman** [comment]
This little script will add members from the website yaml file to the github org:

```Python
from github import Github
import yaml


def main():
    # authentication with GitHub
    g = Github('SECRET')
    org = g.get_organization('pangeo-data')

    # people.yml is in the pangeo docs
    with open('./people.yml') as f:
        people = yaml.safe_load(f)

    github_ids = [p['github'] for p in people]

    # pangeo-members = 2180253
    team = org.get_team(2180253)

    # get existing GitHub members
    existing_org_logins = list(member.login for member in org.get_members())
    existing_team_logins = list(member.login for member in team.get_members())

    # add those members not yet in the GitHub org
    for member in github_ids:
        user = g.get_user(member)
        print(user)
        if member not in existing_org_logins:
            print(f'--> adding {member} to org')
            org.add_to_members(user, role='member')

        if member not in existing_team_logins:
            print(f'--> adding {member} to team')
            team.add_membership(user, role='member')


if __name__ == "__main__":
    main()
```

How do we feel about automating this as part of the doc build?

**Comment by mrocklin** [comment]
There are many more members, but almost all of them are private.  You can
change your visible membership to public.

**Comment by rabernat** [comment]
The pangeo-members team currently has write access to the main pangeo repo (this one). That is probably not what we want.

We should think about how to structure the github teams to manage access.

**Comment by jhamman** [comment]
I've taken write access away from the pangeo-members team. I think we should move to a place where smaller teams have admin/write access to specific repositories. 

- pangeo-members: all members of the pangeo GitHub org - read access to all pangeo repos
- pangeo-admin: limited group of pangeo developers - admin access to all pangeo repos
- various smaller teams for managing repo specific admin/write access control (e.g. pangeo-astro).

**Comment by scottyhq** [comment]
The website currently states ["Don’t hesitate to ADD YOURSELF to the list"](http://pangeo.io/collaborators.html#people) but it's not clear how to do that... If I remember correctly, a user has to fork this file: https://github.com/pangeo-data/pangeo/blob/master/docs/data/people.yml and then submit a pull request? Maybe we keep people.yml in a separate place that is completely open access? Maybe the repo wiki (https://github.com/pangeo-data/pangeo/wiki)?

**Comment by mcgibbon** [comment]
This is maybe where this reply to posts in #383 should go? It's about how we communicate as a group.

@jhamman I would suggest using the mailing list for things like #383, #417, #391, #374 whose intended audience is everyone in the group rather than those working on particular projects. It may be appropriate to put discussion in a github issue but announce the existence of that issue to the mailing list for things like #383, #403, where wider announcement is intended but github is useful for organizing and presenting the discussion, which is task-oriented in nature.

It also may be more accessible to separate organizational issues and website issues into different repositories - this repo is *very high* volume, currently accounting for about a quarter of all emails I receive and more e-mails than I receive from all official sources at my institution.

If repos were separated like that, such that everything in the organizational repo is something that should be sent to all members, it might be possible to have a bot automatically notify the mailing list about new issues in the github repo. Or it may be possible to sign the mailing list up to notifications through Github.

**Comment by guillaumeeb** [comment]
FWIW, I like the fact that everything is done in one tool. It may need some refactoring or more structuration on how to use it, but I still prefer that to splitting things in different channels.

**Comment by chiaral** [comment]
Regarding Github as main mean of communications - and all the good points brought up by @mcgibbon in #383.

1) I like one tool too. Personally I have found myself in groups trying to communicate through too many tools loosing then track of all of them and going back to just emailing each other files (I know not very productive!)

2) I think we all agree with his points to restructure some repos to be more subject specific and then send some announcement to a mailing list (we can then re-evaluate that if the mailing list keeps being unused and unsubscribed to).

3) regarding Github and the barrier that it represents to women (and not only) to join open source project, I definitely had the same experience, but I think we should double down on Github rather than leave it behind (I know no one is suggesting that), because after all we do want more women to join it! 

I think that a way to help people that are new to Github to join is to make very clear (through clear instructions on the website? once a month reminders sent to the mailing list? all of the above and more?) that first of all Github can definitely be used as a mailing list tool, at least as we are doing it here in Pangeo, and then much more. That people can totally sign up for it and just use it to communicate, and that all the fork, pull, push, merge and yadda yadda yadda lingo represent to some extent added layer to the "social side" of it.

My personal experience was that I thought it was only to do the code repo, so I hesitated to join in. Then I realize the very large social aspect of it (at least within the Pangeo community) and happily subscribed to many repos. Then by reading threads, and getting more acquainted to how things move along within a project, I felt encouraged to add some help for example to the xarray manual. 

So my vote is to stick to Github, restructure it to have repos that are more focused on a specific topic, beside a general one of course, and keep using the mailing list for general announcements (and then recalibrate it in a few months), and add and make very clear (I can draft something) how Github is used, within Pangeo, to communicate, that it is open to everyone and fairly easy to use, for the purpose of communication.
