### ISSUE TITLE
Educational materials

### ISSUE THREAD

**Issue by DamienIrving** [pangeo-data/pangeo#411]
I recently launched Data Carpentry lessons for atmosphere and ocean scientists:
https://datacarpentry.org/blog/2018/09/atmos-ocean-launch

If anyone in the pangeo community has ideas for additional lessons they'd like to see added, feel free to let me know 😄

**Comment by mrocklin** [comment]
I'm really glad to see this.  I think that educational outreach is one of the main things that we should be focused on.  XArray's tooling in particular seems to have surpassed adoption today (more people should be using it than do today).  I think that developing and delivering resources like this are probably also excellent places for institutions to start participating.

cc @stephansiemen

**Comment by rabernat** [comment]
Fantastic Damien! We would love to work with you to develop more lessons. 👍 to what @mrocklin said.

**Comment by marylhaley** [comment]
Damien and I had a conversation a few days ago around his Data Carpentry lessons and what extensions might be useful. The two topics that came up for further lessons were dask and regridding. Based on an NCL survey we conducted awhile back, I think there could be a huge demand for training on a wide range of Python topics, from beginner stuff to advanced xarray, plotting, regridding, file writing, etc.

I'd like to float the idea of bringing Damien to NCAR to teach his pyaos lessons (I know we'd have a lot of local interest) and then have a discussion about developing some more lessons.  Ryan May said they have a suite of lessons to contribute.

**Comment by venitahagerty** [comment]
I'm over at NOAA/OAR/ESRL/GSD in Boulder, and we have people here who would also be interested in training for Pangeo, Python, xarray and dask for atmosphere scientists.

**Comment by rabernat** [comment]
Hi @marylhaley  and @venitahagerty -- thanks a lot for your comment and sorry for the slow reply.

We would love to support the development of more educational materials in any way possible. I agree completely that this is a really important area to focus on.

FYI, I am currently teaching a full credit class on "research computing in Earth Sciences":
https://rabernat.github.io/research_computing_2018/

I eventually hope to repurpose much of this material for an python / xarray / pangeo tutorial. Perhaps it could also be published via data carpentry.

**Comment by jhamman** [comment]
I don't think this issue is ready to be closed. I spoke with @amanda-tan and @robfatland yesterday, both of whom voiced interest in helping develop additional Pangeo educational materials.

I think they have some ideas of their own but I'll share a few of mine that cover what I'd like to see done:

- I think it would be great if we created a pangeo-elements tutorial. I'm envisioning something like the dask-examples repo/binders but with a bit more of a Pangeo bend. These would be significantly less involved than the the notebooks currently in the pangeo-example-notebooks repo.
- We should also find a way to present examples on the pangeo website from various repos. We currently have http://pangeo.io/use_cases/index.html, but this is a bit out of date. It would be great if it was easier to reference notebooks/examples/tutorials from other sources and link to a run-able binder.
- Finally, tutorial and course materials. We have built a bunch of material over the last year but have not settled on a format (or a collection of formats). I think there is room for someone to help codify some of this work.

**Comment by robfatland** [comment]
Chiming in: I agree. Amanda and I are essentially signing on to help drive outreach for pangeo; and for context we are involved in OOI at UW (oceanography), with NASA HIMAT (snow hydrology in high mountain Asia), with pangeo of course, we are doing an incubator with a NOAA postdoc doing ML on TRMM, and as if that weren't enough I'm also banging away on the Scambos et al GlObal Land Ice Velocity Extraction (GOLIVE) dataset. So you might be tempted to roll your eyes (we roll our eyes at ourselves a lot) but my point is there is a ton of thematic overlap and I feel very strongly about The Last Ten Yards Of Adoption. So pardon my polemical tone for a moment: You can't get pangeo until you get dask until you get xarray (etc pandas ndarray numpy...) until you get NetCDF until you get ipyleaflet until you get pyplot subplots.... and this is just a Python approach. So with that daunting prospect I'd be shocked by *healthy* adoption rates. The only way I can see forward is to wade into this stuff -- which is what I've spent intermittent jags of time doing over the past year -- to articulate for the prospective adopter what is important. I have three therefores to run by you, then...

* Therefore I will go back through Damien's work from last October and get up to speed (+ any other stuff; please advise) 
* Therefore I will articulate where I am coming from / progress better in the near future. The pangeo-data 'cmr' repo is where my Jupyter notebooks are piling up. The principle/recent such is a model for an executable paper ('golive'). It is a random walk through 'Until You Get' space.
* Therefore I recommend we get together in Boulder or Seattle in the spring if it seems like we have the critical mass and can use the f2f bandwidth; otherwise we can do Zoom

Let me know if you have advice/direction for us and generally whether this seems on track.

**Comment by amanda-tan** [comment]
Just randomly and in the vein of building blocks, here is my word vomit:  I think CF-compliance is grossly overlooked and I wonder how it fits into the grand scheme of educational materials for Pangeo. It seems to me that a lot of the problems that are encountered particularly with xarray is the fact that the NetCDFs aren't formatted properly. For example, if someone has a bunch of NetCDFs that has wrong dimensions (like no time stamp), they are more likely to say that the system doesn't work and get frustrated as opposed to actually looking at the NetCDF file and realizing there are ways to fix it. 

I like the idea of a Software Carpentry style workshop where you start with the core elements like what goes into a NetCDF file and build it to the point that someone can use Intake or OpenDAP to open a bunch of files and run some analysis. A bunch of notebooks with pre-canned scripts and access to a Pangeo deployment is one thing (essentially saying, hit shift-enter and go nuts); I think people really need to see a pathway to their own use case, that the system is adaptable and easy to understand and that it won't take them two years to get to a point where they can run something. There are a lot of systems out there built with the prime motive to impede progress, I believe Pangeo isn't and we just need to convince people that is the case.

**Comment by rabernat** [comment]
We need to keep this open.
