### ISSUE TITLE
Where can we find the documentation for using pangeo on Cheyenne?

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#458]
@roxyboy would like to know.

Many @andersy005 knows something about this?

**Comment by mnlevy1981** [comment]
The best place to start is probably [NCAR/pangeo](https://github.com/NCAR/pangeo) -- the documentation isn't fully fleshed out yet, but it should walk through setting up an environment with dask-jobqueue 0.4.0 and also help connect to the cluster's instance of jupyter lab from a local machine.

I don't know if [NCAR/pangeo-tutorial-august-2018](https://github.com/NCAR/pangeo-tutorial-august-2018) still provides a useable environment, but if it does the [last example](https://github.com/NCAR/pangeo-tutorial-august-2018/blob/master/notebooks/3.1.cheyenne_example.ipynb) was designed to run on cheyenne.

At one point @kmpaul and I talked about asking CISL to update the documentation on the CISL [page about Jupyter](https://www2.cisl.ucar.edu/resources/computational-systems/cheyenne/software/jupyter-and-ipython) but I don't know that we ever did that. (I know that I never did that, not sure if Kevin did.)

@roxyboy, the main keys are

1. install conda in your `/glade/work` space (don't rely on the CISL-maintained python environments)
2. use nbserverproxy so that you only need to forward one port from the cluster to your local machine (requires dask-jobqueue >= 0.4.0)

**Comment by andersy005** [comment]
@roxyboy, one more thing to add - there is an **unofficial** conda module on cheyenne in case you would like to bypass conda installation part:

```bash
module use module use /glade/work/abanihi/softwares/modulefiles/
module load conda # Load the module
```
Once this is done, you will have a **read-only** conda root environment. However, you still need to create your own conda **environments**.

**Comment by rabernat** [comment]
Thanks @mnlevy1981!

How can we make this more findable? For example, there is no link to any of this from the main deployments page:
http://pangeo.io/deployments.html

Suggestions welcome!

**Comment by roxyboy** [comment]
Thanks for all the help! I just installed miniconda onto my account and set up a conda environment.

**Comment by rabernat** [comment]
What if we modified the "deployments" page so we could provide links to the deployment-specific documentation?

**Comment by guillaumeeb** [comment]
There is also the PR #304 that has not been merged yet!
