### ISSUE TITLE
GCS FileSystem for JupyterLab

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#46]
When manipulating data and notebooks on Google Cloud I often wish I could easily manipulate my GCS bucket as a file system in Jupyter Lab, for example by uploading/opening notebooks or moving files around by clicking, dragging, and double-clicking. 

Apparently JLab has nice interfaces for this that have already been implemented for Google Drive and Github (read-only).  It might be useful for us to do the same for GCS.  

- Google drive code: https://github.com/jupyterlab/jupyterlab-google-drive/blob/master/src/drive/contents.ts
- Github drive code: https://github.com/jupyterlab/jupyterlab-github

This would benefit me personally (I would just maintain my notebooks in a GCS bucket) and I suspect that it would more significantly benefit less technical users.

cc @bollwyvl

**Comment by mrocklin** [comment]
@bollwyvl also pointed me to https://cloud.google.com/storage/docs/gcs-fuse which seems pleasant

**Comment by bollwyvl** [comment]
So there's some bits that can be fiddled to make this work.

- filesystem: using the FUSE API identified, move this fully to a non-jupyter-managed configuration experience... though with a freaky serverextension, it could probably _also_ be configured at runtime. You'd lose some stuff, like ACLs.
- `notebook` : A server-side `ContentsManager` would make the files available to all of the notebook stuff. You'd put the API keys into some configuration place. This could either expect the _entire_ notebook directory to be served from a single bucket, or have a virtual directory that used bucket ids or something, again maybe with a freaky serverextension. This would _also_ work with notebook classic and other frontends.
- `jupyterlab`: As identified above, a labextension implementing the `IDrive` interface, backed by the [firebase SDK](https://firebase.google.com/docs/storage/web/start) and would likely be very similar to the existing implementation for the drive API. The handshake would be entirely done client-side.

A rough sketch of how you think your users might want to use this (multiple buckets, multiple accounts, accessing files in kernels, etc.) might help guide the decision.

It's hard to estimate which of these would be the least work vs most reward. Presumably, the labextension approach would be the most flexible, since it doesn't need any information at startup. The not-managed-by-jupyter-at-all approach might appear the most seamless, and would also make neighboring files available to kernels (probably), but does increase the setup burden. The ContentsManager falls somewhere in between.

**Comment by mrocklin** [comment]
@danielfrg has a `ContentsManager` solution for S3 here I believe: https://github.com/danielfrg/s3contents

It seems feasible to convert that to use GCS decently easily.  This is a bit less attractive than a full JLab solution, especially if people want to manage their non-notebook files in GCS.  It's not yet clear how likely this is to be important.  I'm pushing for it though.

**Comment by mrocklin** [comment]
> A rough sketch of how you think your users might want to use this (multiple buckets, multiple accounts, accessing files in kernels, etc.) might help guide the decision.

Lets ping @rabernat and @jhamman for this, I suspect that they have a better understanding of how science users think than I do. 

My guess is that we could live within a single bucket for a fixed set of specified buckets. (it's not clear how this would work for all buckets everywhere).  I would expect to authenticate either through cloud tokens (google seems to be good at this) or by using `gcloud auth login`.  I don't think that we need to access data from kernels, we have good Python-based alternatives for this that we're quite comfortable with.

**Comment by bollwyvl** [comment]
> It seems feasible to convert that to use GCS decently easily. 

Or indeed, just use the feature [merged a few days ago](https://github.com/danielfrg/s3contents/pull/25)!

**Comment by danielfrg** [comment]
Yes, I pinged @mrocklin on that but not here, sorry about that but yeah I added support for GCS this weekend. It passed tests on my setup but its not as tested as S3. I bet it works fine and more testing would be nice.

**Comment by rabernat** [comment]
Our short term and long term needs are quite distinct.

In the short term, we need <10 trusted users to have some sort of persistent filesystem from which they can clone, edit, execute, commit, and push notebooks and other scripts to / from github. Ideally each user would have his own home directory, similar to what one gets on a traditional shared HPC system. Terminal access to this filesystem would be important. The easiest thing I can think of is to just create a persistent disk in GCP for each user. 

In the long term, we would need a more flexible system for managing a larger number of users. Without terminal access, we would need to figure out a different mechanism for uploading / downloading notebooks and / or syncing with github.

**Comment by mrocklin** [comment]
If you want terminal access then I personally would just use the `gcsfuse` approach.  I ran it locally and it worked decently well.

**Comment by mrocklin** [comment]
I've created a multi-region `pangeo` bucket.  I was able to mount it on my local file system as follows:

```
export GCSFUSE_REPO=gcsfuse-`lsb_release -c -s`
echo "deb http://packages.cloud.google.com/apt $GCSFUSE_REPO main" | sudo tee /etc/apt/sources.list.d/gcsfuse.list

sudo apt-get install gcsfuse

sudo mkdir /gcs
sudo chown -R $USER.$USER /gcs
mkdir /gcs/pangeo

gcloud auth login  # assuming you have gcloud, get credentials

gcsfuse pangeo /gcs/pangeo
```

```
mrocklin@carbon:/gcs/pangeo$ tree .
.
├── mrocklin
│   └── start.ipynb
└── test

2 directories, 1 file
```

**Comment by rabernat** [comment]
Perfect. Can this become part of the general GCP config / documentation that @mmccarty is developing for #16?

**Comment by mrocklin** [comment]
My guess is that we would put whatever solution we come up with into a
Dockerfile that would run on setup.

I'm working on these things now.  It would be useful to have a high
bandwidth conversation on this topic.

**Comment by rabernat** [comment]
I'm free to chat for the next hour.

**Comment by mrocklin** [comment]
I'll be here for a bit: https://appear.in/pangeo
