### ISSUE TITLE
help setting up atmos.pangeo.io

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#460]
We want to create a new pangeo cluster: atmos.pangeo.io, focused on atmospheric science). The initial scope is to create a shared environment for data and analysis for the [TRACMIP](https://sites.google.com/site/tracmip/) project. If this is successful, we can try to expand to cover a broader segment of the atmospheric science community.

Customizing this cluster will be the task of @charlesbluca, a Columbia computer science student and intern here at Lamont, with supervision from me and @biasuttimic. As Charles is new to cloud tech and has limited time, we would definitely appreciate getting a head start from @dsludwig in terms of initial creation of the repo / cluster (as done for example with astro.pangeo.io). Then Charles can take the lead on configuring the domain-specific aspects of the cluster.

Very excited about this one.

**Comment by dsludwig** [comment]
I've got a cluster up and jupyterhub installed. I still need to adjust some of the configuration, but first I need DNS set up: 

atmos.pangeo.io   35.184.25.194

**Comment by jhamman** [comment]
@dsludwig - done!

**Comment by dsludwig** [comment]
This cluster should be set up and ready to go. I made a couple enhancements: user notebooks and dask workers schedule onto different node pools, and those pools are tainted so that they scale down quickly as well (no system components schedule onto the nodes).

I tried to give @charlesbluca and @biasuttimic access, but they're not members of the pangeo-data org yet, so I can't add them to the team. I haven't been able to find the invite button, either.

**Comment by mrocklin** [comment]
I've added @charlesbluca and @biasuttimic to the pangeo org.  You two will have to make your membership public by visiting https://github.com/orgs/pangeo-data/people and changing your membership to public.

I've also given @dsludwig ownership permissions over the org (after consulting with @rabernat )

**Comment by dopplershift** [comment]
Where's the environment for this one controlled?

**Comment by dsludwig** [comment]
The repository for this one is here:
https://github.com/pangeo-data/atmos.pangeo.io-deploy
