### ISSUE TITLE
Pangeo talk given at ESA Earth Observation Φ-week AWS Earth side event

### ISSUE THREAD

**Issue by tam203** [pangeo-data/pangeo#479]
Just an FYI to say that I gave a talk on Pangeo at the ESA Earth Observation Φ-week event. There was an Earth on AWS session that I presented at on behalf of Pangeo, Met Office and Informatics Lab.

Slides here if interested: https://docs.google.com/presentation/d/1XKy4rbHPuoHk2PqiUTVaXBwm2Uo8wtV6wgzQzB-M6CQ/edit?usp=sharing 

Lots of intrest and enthusiasm which was good.

**Comment by jhamman** [comment]
@tam203 - thanks for sharing your slides. Three cheers for @jacobtomlinson having a fargate demo ready to show after just a few days of work!

**Comment by jacobtomlinson** [comment]
Here is the fargate example notebook that @tam203 linked to in the slides

https://gist.github.com/jacobtomlinson/ee5ba79228e42bcc9975faf0179c3d1a

I'm still working on turning this into `dask-fargate` but it's taken a bit of a back seat since discovering how expensive and limited fargate actually is.
