### ISSUE TITLE
Set up adaptive deployment on Cheyenne

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#51]
It might be convenient to set up a long-running dask-scheduler on Cheyenne that is capable of adaptively asking for more workers as needed and releasing those workers back to the job scheduler when not needed.  This would be helpful in allowing us to scale up when necessary without incurring significant costs.

From a talk with @jhamman it may also be valuable to have a long-running scheduler that other people outside of the group can use without having to set anything up.

**Comment by jhamman** [comment]
@davidedelvento - I'm wondering if you can give us some ideas for how this may work on Cheyenne.  The concept here would be that we have a dask-scheduler running all the time and workers are spawned when there is work to do. Dask can handle the spawning of new workers via PBS but we would need to be able to maintain a long running process for the scheduler.

One idea would be to run a scheduler task on one of the login nodes. That is not particularly ideal but may be the only solution for a long running task at this time.

**Comment by davidedelvento** [comment]
This is very hard to fly, for various reasons, but let discuss the first ones that come to mind:

* Do you need one scheduler for each user, or do you need one period? In the former case, there are too many users to be scalable. In the latter you probably need root to switch users, which they will not give to you (they don't give it to me either, FWIW)

* Even assuming that the previous issue is solved, most HPC datacenters have a few to several login nodes (6 on Cheyenne). You will have to deal with this complexity. Moreover, each one of them may go down at any time and it may be the one where your scheduler is running. So to make your code robust, you have to deal with the scheduler not running anyway. Then, why not make "not-running" the default (at least in some configurations, such as the HPC one) and start it only when needed with an option to shut it down when "done"? Of course one need to define "done" properly

* Assuming "not running" is the default, what prevents you from using the share queue (or geyser/caldera queues in the case of Cheyenne) instead of the login nodes? This would be more friendly to fellow users (the login nodes are often crowded) and also more robust: the login nodes are often abused, (hence they may go down at any time per previous bullet, but even if they don't go down) they may be very slow (to prevent this we plan to deploy a watchdog which will kill what it deems abusive processes, such as long-running ones... on Yellowstone such a watchdog is already in place)

**Comment by mrocklin** [comment]
Yeah, we might consider making a Python object that launches a dask scheduler.  This might be as intuitive for users as an always-on scheduler.  

```python
from pangeo import CheyenneCluster
cluster = CheynneCluster()  # qsub's a single scheduler job, blocks until it starts running
from dask.distributed import Client
client = Client(cluster)

... do XArray work
```

The time delay on this wouldn't be that great.  Is there an already established way for users to get a Jupyter notebook or other single-node interactive computing environment with their own Python environment?

**Comment by davidedelvento** [comment]
1. do you really want to make it Cheyenne specific like that? I'd make it generic such as `cluster = Cluster()` and make it an installation setup to decide what needs to happen. It could be anything from "nothing", to "submit a qsub job and wait", to "submit a job with LSF, slurm or whatever", to "do something with kubernete" or who knows.

2. Regarding your question, one way is qinteractive as described at https://www2.cisl.ucar.edu/resources/computational-systems/cheyenne/running-jobs/submitting-jobs-pbs --- another way is what @kmpaul and I are trying to do, namely slide 9 and subsequent of [this presentation](https://docs.google.com/presentation/d/1vxtRaeju7qWrb_RXcsh-m2lKEDZoFBCJE0SWOMi-wNo/edit#slide=id.g2c7dc84059_0_204)

**Comment by mrocklin** [comment]
> do you really want to make it Cheyenne specific like that? I'd make it generic such as cluster = Cluster() and make it an installation setup to decide what needs to happen. It could be anything from "nothing", to "submit a qsub job and wait", to "submit a job with LSF, slurm or whatever", to "do something with kubernete" or who knows.

No, I don't want to make it cluster-specific.  My guess is that this will need to be somewhat specific to different hardware though, at least due to things like different job schedulers.

**Comment by mrocklin** [comment]
> Regarding your question, one way is qinteractive as described at https://www2.cisl.ucar.edu/resources/computational-systems/cheyenne/running-jobs/submitting-jobs-pbs --- another way is what @kmpaul and I are trying to do, namely slide 9 and subsequent of this presentation

What is the status on your JupyterHub work?  Do you have a sense for when this will be deployed, at least for early adopters?

**Comment by mrocklin** [comment]
https://github.com/pangeo-data/pangeo/pull/56

**Comment by davidedelvento** [comment]
@mrocklin @kmpaul  Re: JupyterHub -- making progress but hard to tell about the deployment, since I don't have even a working proof of concept now. The problem is that I have a gazillion of projects on which I'm working on (and one of them is dealing with the huge amount of emails I receive which require attention, such as this one ;-) )
Happy Holidays

**Comment by jhamman** [comment]
I think we can close this for the time since #56 was merged.
