### ISSUE TITLE
I can't access "https://ocean.pangeo.io"

### ISSUE THREAD

**Issue by adeajayi-kunle** [pangeo-data/pangeo#559]
Hi, 

I have been trying to access https://ocean.pangeo.io with my Github account but all I get is "403 : Forbidden". 

Can anyone please tell me how to solve this problem.

Thanks

**Comment by rabernat** [comment]
Ajayi - this is because you're not part of the pangeo organization or don't have your membership listed as public. We are currently in the middle of a big refactoring of our clusters. Within a few days we should have a new system in place that is easier to access. See https://github.com/pangeo-data/pangeo-cloud-federation/issues/60 for more info.

**Comment by adeajayi-kunle** [comment]
As regards to Pangeo organization/ membership, are you referring to the collaborators' list? If yes how do I add myself?
