### ISSUE TITLE
Weekly checkin meeting 2019-03-06 15:00 EST

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#568]
Hi folks, we have a weekly checkin today.

Some possible topics for discussion:
- Update on pangeo Earthcube proposals 
- Status report on new cloud hubs (we made big progress this week!)
- Update from machine learning working group
- Update from potential new "grids" working group

https://appear.in/pangeo

**Comment by ktyle** [comment]
Having just fortuitously stumbled onto @JiaweiZhuang 's tweets of today, which prompted a chat with @rsignell-usgs perhaps a discussion of Jiawei's methods on AWS would be interesting ...

**Comment by rsignell-usgs** [comment]
Jiawei's blog post: [Experiments with AWS FSx for Lustre: I/O benchmark and Dask cluster deployment](https://jiaweizhuang.github.io/blog/fsx-experiments)

**Comment by JiaweiZhuang** [comment]
Glad to see some community interests! I can join the meeting if that helps.

**Comment by rabernat** [comment]
@JiaweiZhuang you're always welcome

**Comment by JiaweiZhuang** [comment]
Want to follow-up on action items but have lost track of the contacts. I will just put things here:

In terms of migration from IDL -> Python/xarray, our GEOS-Chem team at Harvard (https://github.com/geoschem) have quite a lot experience...  Over the past ~15 years our official data analysis tool is an IDL-base package (http://acmg.seas.harvard.edu/gamap/). We now have a Python package under construction at 
- https://github.com/geoschem/gcpy. 

It turns out that xarray itself can get 90% of the things done out-of-box, so as a quick solution I wrote an xarray tutorial at 
- https://github.com/geoschem/GEOSChem-python-tutorial. 

Our users seem pretty happy with it and happy to make the transition (https://github.com/geoschem/geos-chem-cloud/issues/21#issuecomment-469068693 being an example).

**Comment by darothen** [comment]
@JiaweiZhuang I'm glad to see that gcpy had some "sticking" power! Your blog posts this morning were fantastic, they generated a huge amount of interest among my team members.

**Comment by JiaweiZhuang** [comment]
@darothen Yes we are moving slowly but steadily (everyone has no little time)! The doc page is still exactly the same as what you made two years ago :)

Glad you find the post helpful -- happy to chat about potential use cases.
