### ISSUE TITLE
Improving our weekly meetings

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#570]
We have been doing weekly online meetings for quite a while now. These are clearly quite valuable in terms of coordinating efforts and building community. But it may also be a good time to assess the structure and effectiveness of these meetings and think about how we can improve.

I recently came across this article which made me think hard about this topic:
https://chelseatroy.com/2018/04/05/how-do-we-make-remote-meetings-not-suck/

The bottom line is that the article recommends using a moderator to make sure everyone has a chance to contribute, to avoid the meeting being dominated by the loudest voices. @mrocklin basically used to play this role for us and did an excellent job. Since he has moved on, I have tried to take over that role...the problem is that I also have a loud voice (high "caucus score") and consequently am ending up talking way to much. Instead of feeling personally guilty about this, the blog post linked above helped me to see it as a structural problem.

Some questions for the community:
- What do we see as the point of these meetings?
- Are we happy with the general structure (quick reports, status checks on longer-term issues) which was originally proposed by Matt?
- Should we adopt the moderator idea? If so, how do we appoint a moderator?
- What is the ideal meeting frequency?

**Comment by mrocklin** [comment]
>  @mrocklin basically used to play this role for us. Since he has moved on

FWIW I'm still around, just not as reliably :)

**Comment by rabernat** [comment]
Of course, and we appreciate your continued involvement! All I'm saying is, we shouldn't count on you to moderate our weekly meetings.

**Comment by willirath** [comment]
@rabernat I liked how in the Monday meeting on #357 you took two minutes to actively discuss moderation and form of the meeting.

**Comment by rsignell-usgs** [comment]
I think the popularity of the weekly meetings indicates they work at some level.  I know I find them useful, because it's really hard to sort through the week's github issue traffic!   The short check in at the beginning does in fact make sure that everyone's voice is heard.   

A possible slight improvement to the check ins?   My wife said in her meetings she had a one minute timer on the table for these type of check ins, to make sure people thought about and were efficient in what they had to communicate.   While it sounds kind of harsh, she said people actually appreciated it.  

If people thought this a good idea, we could display a one-minute timer on the shared screen or something.

**Comment by jhamman** [comment]
In lieu of @rabernat leading tomorrow's meeting, I'm going to take over and try out few slight modifications to the meeting format. 

- Crowd source the meeting agenda ahead of time (google doc link is included in #571). Try to finalize the agenda ahead of time (with the exception of the quick updates).
- Keep quick updates to 60 seconds
- Separate agenda times for project reports/celebrations and larger agenda items.
