### ISSUE TITLE
CMIP6 and Pangeo

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#579]
We are trying to think about how Pangeo can help with the CMIP6 process. There is a very short window between when the CMIP6 data is being released and the due date for the next IPCC report (31 December 2019). This is a strong motivation to deploy the sort of scalable, data-proximate computing approach championed by Pangeo. This could happen at traditional HPC centers like NCAR, DKRZ, CEDA, etc. There could also be a role for our commercial-cloud-based deployments.

To demonstrate the possibilities, we have zarrified some CMIP6 data and placed it in Google Cloud Storage (see [CMIP6 intake catalog](https://github.com/pangeo-data/pangeo-datastore/blob/master/intake-catalogs/cmip6.yaml)). And I created a binder demo that targets this data with some xarray / dask -based analysis: https://github.com/pangeo-data/pangeo_cmip6_examples

@balaji-gfdl recently shared this at the [CMIP6 Model Analysis Workshop](https://cmip6workshop19.sciencesconf.org/) in Barcelona (xref #339). There was some interest from the CMIP community.

Let's use this issue to discuss the best ways to move forward with this initiative. I'm particularly interested in hearing from scientists what sort of data analysis and workflows you are finding challenging with your current infrastructure.

**Comment by balaji-gfdl** [comment]
Sorry it took a while, but the priority list of variables is available now.

Please see https://docs.google.com/spreadsheets/d/1H2qXofwjOpCospDcj9LRokpz0HGysRcDK2HmNSJoqyk/edit#gid=0

An official letter will be going out in the next few days, it will say approximately this:

To Modeling Groups and Other Concerned Parties:

We  hope that your CMIP6 activities are proceeding satisfactorily. The WIP and the CMIP Panel wish to publicize the list of variables that the IPCC Authors have identified in a survey as being of highest priority for IPCC-AR6 in a survey concluded in March 2019. We thank Jasmin John, NOAA/GFDL for her role in collecting this information.

While CMIP6 is nominally independent of IPCC, the WIP and the CMIP Panel concluded during the recent WGCM-22 meeting in Barcelona, 29 March 2019, that this list of variables may aid the groups publishing and distributing data in assigning priority. Modeling groups may wish to use this list in prioritizing and accelerating their internal scientific quality control for these variables. Publication teams may wish to use this list to ensuring these variables appear as quickly as possible on their ESGF data node. The CMIP6 Data Node Operations Team (CDNOT) and others may use this list as guidance in deciding which variables to replicate and make as widely available as possible.

We also draw your attention to the IPCC Calendar. In particular the 3rd Lead Author meeting IPCC-LAM3 in Toulouse, France, 26-30 August 2019.

The science of CMIP6 will continue independently of IPCC, and for this the community can continue to use the experiment tiers and variable priorities already assigned by the CMIP Panel and MIP Chairs in the CMIP6 Data Request.

**Comment by rabernat** [comment]
@naomi-henderson - how do you feel about preparing the AR6 WG1 priority variables for cloud storage? Is this something you have bandwidth for? It looks mostly like stuff Haibo will have already wanted to download for local analysis. 

Maybe Charles can help with this too...

**Comment by naomi-henderson** [comment]
@rabernat , yes I could get started on this. It is extremely useful to have @balaji-gfdl 's document as a roadmap for creating the directory structure and catalog.  Since the current number of models is still quite limited, we need to carefully build methods to continually update the collection as it comes in.  Yes, fortunately Balaji's list looks like a subset of what Haibo will be collecting, anyway. 

I think it is best for us to collect and 'zarr-ify' the data here at LDEO so we can the collection processes running in the background.  Directly transferring data from ESGF to cloud and then converting to zarr seems less attractive since we are already set up here.

Question: We don't serve zarr data here, we are mostly just keeping the original netcdf files, along with our processed products (multi-model means, budgets, statistics, etc).  But if I delete the zarrs after uploading to GC, can we then propagate the collection from GC directly to S3 and Azure?  Or should I keep the zarr data on our machines to upload directly? Ideas?

**Comment by balaji-gfdl** [comment]
Thanks @naomi-henderson and @rabernat . Is data volume a consideration in this decision? I have made some projections of how much data this might be, and could try to make it more precise. (It's based on some guesswork re how many models, what resolutions, how many ensemble members...)

**Comment by naomi-henderson** [comment]
Yes, @balaji-gfdl , it looks like the data volume will be a consideration. For example, just the `historical` ocean (for CMIP, not for the chapter 9: HighResMIP, OMIP or FAFMIP),  is currently over 17Tb at LLNL since it includes the 3d variables (thetao, so, uo, vo, umo, vmo).

It is possible to compute the sizes, using @rabernat 's [search.py from esgf2xarray](https://github.com/pangeo-data/esgf2xarray/blob/master/esgf2zarr/search.py) to get the basic information (including file sizes) for all of the files in the [AR6-WG1 spreadsheet](https://docs.google.com/spreadsheets/d/1H2qXofwjOpCospDcj9LRokpz0HGysRcDK2HmNSJoqyk/edit#gid=0) .  Then I can get sizes by `activity_id` (CMIP, AerChemMIP, ScenarioMIP, etc), by `table_id` (Amon, Omon, etc) or by `experiment_id`, etc.  I have done this for the CMIP-historical experiment, and am planning on doing it for the whole spreadsheet.

So it looks pretty daunting ...  It looks like we need to prioritize. Ideas?

@rabernat - how much space can we use?  Converting to zarr will take time, I will certainly appreciate any help that Charles can provide.

**Comment by balaji-gfdl** [comment]
I'm surprised by that 17TB figure. Assuming the recommended 1-deg grid, 150yr of 6 3D monthly variables saved at 4 bytes is 360*200*50*12*150*6*4 is 155 GB per ensemble member. Are there really 100+ ensemble members there already?

But I agree that the 3D ocean variables make up the bulk of the recommended variables, most everything else is 2D. (You need to include volcello, masscello, thkcello as well if you want to compute volume integrals, so that brings it up to 9 3D fields and 225 GB).

**Comment by naomi-henderson** [comment]
For `historical`, there are 110 ensemble members, and, for example, the total size of `thetao` is 2,450G.  Here is a table of the sizes and ensemble members for each model:

  [AR6-sizes.pdf](https://github.com/pangeo-data/pangeo/files/3139434/AR6-sizes.pdf)

I think  volcello, masscello, thkcello are fixed in time, so much smaller, no?

**Comment by naomi-henderson** [comment]
@balaji-gfdl  and @rabernat , here are today's total sizes of the AR6-WG1 variables from the spreadsheet - all experiments.  These are just at LLNL - there are more at the other ESGF servers (mostly IPSL) but they are not included here.  The total so far is 46,073 G in 41,669 files.

This is the breakdown by `activity_id`:
[AR6-sizes-2April2019.pdf](https://github.com/pangeo-data/pangeo/files/3139498/AR6-sizes-2April2019.pdf)

and here is a breakdown by `frequency`:
[AR6-SizeByFrequency.pdf](https://github.com/pangeo-data/pangeo/files/3139540/AR6-SizeByFrequency.pdf)

**Comment by balaji-gfdl** [comment]
> I think volcello, masscello, thkcello are fixed in time, so much smaller, no?

Unfortunately not if the model uses a fancy vertical coordinate whose z-location is time-dependent...

**Comment by naomi-henderson** [comment]
Ah, you are correct.  It looks like (at least so far at LLNL), volcello's are all fixed in time, but masscello and thkcello are not.

**Comment by jhamman** [comment]
Based on recent conversations on the subject, I think we can summarize the current state of this issue as:

1. There is growing interest in a Pangeo/CMIP6 platform
1. We can, with existing funding, continue to support prototype efforts
1. We have not identified adequate staff funding to manage a full fledged community cloud based CMIP platform
1. We cannot, with current cloud computing awards, store enough CMIP6 data to serve the full CMIP6 community.

I'd like to suggest we write up two 1-2 page proposals with the hope of attracting some additional resources to make this happen. The first would be targeted at funding agencies (NSF/DOE/DOD/NOAA), making clear the social and scientific benefits of such an effort, and estimating what we think it would be cost to make this viable. The second would be targeted at the cloud providers (GCP/AWS/Azure), laying out a concept for publishing CMIP6 data as part of the public dataset programs.

**Comment by nschiraldi** [comment]
Could there be any benefit to encouraging researchers/universities to serve subsets of CMIP6 over cvmfs? I don't know if cvmfs is really designed to handle the volume of data CMIP6 generates, but I have heard of folks serving NCBI data to Galaxy (biology) instances via cvmfs which can be quite large. 

If the cloud resources are not available, maybe pangeo should explore this as an option?
https://cvmfs.readthedocs.io/en/stable/cpt-repo.html

**Comment by rabernat** [comment]
Follow up to this thread: Pangeo partnered with Google Cloud to bring CMIP6 to their public datasets program.

https://cloud.google.com/blog/products/data-analytics/new-climate-model-data-now-google-public-datasets
