### ISSUE TITLE
Big GCP charges for data transfers between cloud regions

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#628]
Overall our GCP storage bill is remarkably stable, but recently I saw some big spikes.

![image](https://user-images.githubusercontent.com/1197350/57670483-7e60b500-75dd-11e9-8e2b-6ce09ba03d01.png)

### Top Storage Charges

| service_description | sku_description | time                                              | cost       |
|---------------------|-----------------|---------------------------------------------------|------------|
| Cloud Storage   | Download Australia                                | 2019-05-09 | 327.192189 |
| Cloud Storage   | Download Worldwide Destinations (excluding Asi... | 2018-12-13 | 265.465225 |
| Cloud Storage   | Download Australia                                | 2019-05-13 | 97.904733  |
| Cloud Storage   | Download Worldwide Destinations (excluding Asi... | 2018-12-14 | 90.241796  |
| Cloud Storage   | Download Australia                                | 2019-05-10 | 82.516355  |
| Cloud Storage   | Download APAC                                     | 2018-12-18 | 59.501727  |
| Cloud Storage   | Download Worldwide Destinations (excluding Asi... | 2018-12-07 | 48.334123  |
| Cloud Storage   | Regional Storage US                               | 2019-04-04 | 37.460364  |
| Cloud Storage   | Regional Storage US                               | 2019-04-30 | 37.371370  |
| Cloud Storage   | Regional Storage US                               | 2019-04-29 | 37.304473  |

It looks like we had tons of data moving between our us-central1 region where it is all stored and Australia during the recent pangeo workshop there.

I think this is an interesting opportunity to learn more about how cloud charges work. (I'm not blaming anyone for this, to be clear, just discussing.) We could have avoided those charges by either:
- using a pangeo cluster in the same region - is the latency from Australia unacceptable?
- using multi-regional storage (considerably more expensive)

cc to @jmunroe, who set up this workshop, to get some input.

**Comment by pbranson** [comment]
I suspect that this was due to the demonstration being ran on AWS (in Australia), however the training material included a number of examples of data stored in GCS. Using the pangeo binder would not have contributed to this.

I think this raises an important and pertinent issue about the total cost of utilising the commercial cloud for large data stores, as whilst the storage cost is relatively easy to calculate, the real-world cost of people actually accessing and using your data outside of host commercial provider is much harder to predict and potentially prohibitive. 

It would be interesting to weigh up the cost of the compute on google cloud vs external compute. I did some rough benchmarking from a HPC centre in Australia which has some very large bandwidth connections to the internet and got some reasonable scaling up to about 2GB/s throughput to AWS S3. 

Given that mirroring the complete CMIP6 is impractical, at the moment the solution seems to be compute next to source. However, what if the pattern that emerges as global bandwidth availability grows is compute against source (because you have access to highly subsidised HPC or your grant is on cloud X but the data is on cloud Y). 

In that context the cost of a reduction on a full 1TB dataset stored in cloud storage (at $0.15/GB to australia from us-east) is at least $150... once.... seems like highway robbery - literally! and CMIP6 is how many petabytes?

So it seems that unless the community can work out some kind of federated cloud (https://github.com/pangeo-data/pangeo/issues/39#issuecomment-379466470) where opening a dataset from a catalogue provides not only a map to a dataset, but also seamless connectivity to the elastic compute capability for reductions to be performed 'in-place', a different costing model is needed for streaming of these cloud datasets. 

At present the egress cost from cloud storage significantly promotes the business case for publically funded research cloud object storage, where presumably data egress would be measured as a KPI of use rather than a dataset publisher cost. In some regards this plays to the heart of FAIR data principles and raises the fundamental question of if data stored in the commercial cloud ["promotes sharing and reuse of data"](https://www.ands.org.au/working-with-data/fairdata). The complete repository of the Australian Integrated Marine Observing System is now in an AWS S3 bucket, it will be interesting to see how the costing of that unfolds over the coming years as systems like Pangeo facilitate takeup of those datasets. 

In Australia, I am hoping that AARNET, Pawsey/NCI and the Australian Research Data Commons can facilitate the establishment and management of such infrastructure.

@markatpawsey @Elwell @luke-catami @Thomas-Moore-Creative

**Comment by jmunroe** [comment]
Yikes, sorry! That was not the intent. Our Pangeo training was running on AWS infrastructure, in part, due to donated credits from AWS. My hope (which seems to have failed miserably) was that this would actually mean we were not spending compute cycles on binder.pangeo.io .

During the actual training day, we weren't able to scale up as many virtual machines as needed to have each participant have their own dask KubeClusters with 20+ workers (it was more like 4 workers per participant.)  We spent the morning of the training on local-only workloads with dask and xarray. It was only a couple hours in the afternoon where participants were invited to investigate on their own some of the larger pangeo examples which pulled from GCP sources. We directed participants to use binder.pangeo.io if they wanted to try the examples with larger numbers of dask workers but I suppose even with just a few dask workers, these examples really do pull down a lot of data in a fairly short amount of time.

While I am embarrassed I was not thinking about the egress charges, we did repeat the training again early this week at a different location this week using only binder.pangeo.io. So, hopefully, we didn't make the same mistake twice.

I see now that egress charges from us to australia on GCP are shockingly high.  I am not sure it would have any different if we had been using GCP datacentres for compute. The lesson here is one absolutely needs to move the compute to where the data is stored.  I knew that lesson from a time/performance perspective, but this incident hits home the need from a financial one as well.

My binderhub instances that were running on AWS was taken down at the end of 2019-05-09 and the subsequent 'Download Australia' costs on 2019-05-10 and 2019-05-13 I suppose are people trying the example notebooks on their own infrastructure.  Is there any way to configure a GCS bucket so that it is restricted to certain regions?

**Comment by jmunroe** [comment]
I don't think multi-region storage would have helped in this case.  GCP description's of 'multi-region' is not the same as a 'global':

Multi-Region Name | Multi-Region Description
-- | --
asia | Data centers in Asia
eu | Data centers in the European Union1
us | Data centers in the United States

( https://cloud.google.com/storage/docs/locations#location-mr )

**Comment by rabernat** [comment]
@jmunroe - no apologies necessary. The point of all of this is to learn how things work. This was a useful learning experience.

Ok @pbranson, thanks for the clarification that the tutorial was running on AWS. Yes, in that case, yes, we will definitely incur major egress charges.

I would resist jumping to overly broad conclusions based on this example, which really represents a worst-case scenario (many simultaneous downloads of the same large datasets from GCP in the US to AWS in Australia). There are lots of ways we could mitigate these costs, including:
- Being more careful about computing in the same cloud / region as the data (the easiest one)
- Using "requester pays" mode to discourage suboptimal workflows
- Taking advantage of [egress waivers for scientific research](https://www.internet2.edu/news/detail/17063/)
- Developing some sort of caching / mirroring system similar to ESGF

> I suppose are people trying the example notebooks on their own infrastructure. Is there any way to configure a GCS bucket so that it is restricted to certain regions?

Yes, we can put them in private mode or "requester pays." Then the users will need to authenticate, however.

**Comment by amanda-tan** [comment]
@scottyhq and @robfatland have been thinking about porting the contents of the Pangeo GCS bucket to AWS (in the context of the ACCESS project) so this is a discussion that we should address especially if we are starting to do more demonstrations on the AWS cluster.

**Comment by robfatland** [comment]
I suggest: Everyone concerned with this should have "ten cents per GB" in mind when thinking about egress cost. 

Allow me to work a cost example for your amusement. 

A demo of @rabernat 's excellent sea level notebook -- supposing the data volume runs to 80GB -- would be *free* on pangeo binder installed on GCP but would carry an implicit cost of $8 in egress fees when running the same demo on the pangeo JupyterHub on AWS.  Why $0 versus $8? In the first case you are staying within the GCP cloud; so no egress. In the second case you egress from GCP to AWS; and note that the ingress to any cloud is free.

Now how much do we pay to store those 80GB on AWS S3 for a year? Answer: $24. So 3 AWS demos = 1 year of data storage in this example; ymmv.
