### ISSUE TITLE
Use of Pangeo on the Pawsey Zeus Supercomputer

### ISSUE THREAD

**Issue by pbranson** [pangeo-data/pangeo#660]
Due to recent changes to the user permissions at Pawsey users are no longer able to write to the volatile /run folder on the compute nodes. This prevented starting of jupyter which tries to write files there.

A work around is to use containers, which I tested out and works quite well, inparticular using Shifter to run the containers:

https://github.com/pbranson/pangeo-hpc-shifter 

This works with the pangeo-notebook image being curated at https://github.com/pangeo-data/pangeo-stacks 

The only short-coming with this approach is that dask-jobqueue doesnt work from inside the container. We had thought about possibly trying dask-drmaa as an alternative as that should be able to interact with the slurm scheduler outside the container to submit jobs. There is no network isolation when working in containers on HPC.

Appreciated anyones thoughts on solutions to this.

**Comment by TomAugspurger** [comment]
cc @guillaumeeb for the (potential) dask-jobqueue issue. Are you familiar with shifter? Does it sound like dask-jobqueue should work from within it?

**Comment by guillaumeeb** [comment]
Thanks for the cc.

I'm not familiar with Shifter, but it seems to rely a lot on Docker. If there is no network isolation when working from the container, then it probably means you just need a way to submit jobs from inside the container, so have some slurm client (sbatch command) accessible from the container. I see two possibilities: 
- either install slurm client in the docker image, and configure it according to your cluster to be able to contact the scheduler,
- or mount the node file system path where Slurm client is installed when launching the container.

I'm not using Slurm but PBS in my cluster, which is installed in /opt/pbs, so assuming the container has the same OS as the host, I would be able to use the client from the host by mounting this directory.

This mays also require some tunning in dask-jobqueue, so that the generated worker job script file also uses Docker/Shifter, and not only a Python command. e.g. : 
```
docker run dask-worker ...
```
instead of
```
python -m dask.distributed.cli.dask_worker
```

These are only some simple thoughts and probably both optimistic and approximative...

Anyway, this is interesting work!

Did you also try running dask-jobqueue from Singularity images? I imagine there would be similar issues, this would be could to tackle them!

**Comment by pbranson** [comment]
> Did you also try running dask-jobqueue from Singularity images? I imagine there would be similar issues, this would be could to tackle them!

https://github.com/pbranson/pangeo-hpc-singularity

Yep, it didnt work as well as in order to get jupyter to run I needed to bind an actual filesystem folder to /run/home so ended up with some junk hanging around. And I still needed to use docker to puild the container as singularity hub was having issues with the pangeo-notebook - something to do with conda clean -tipsy 

The way shifter handles volatile files and having the per-node-cache is pretty convenient, so decided shifter was better in this instance. 

Certainly for both these approaches, having python and its dependencies inside the container makes the whole jupyter experience much more responsive. 

I did see one hack where you could 

'alias sbatch=ssh localhost sbatch' if you have ssh certificates set up, however was advised that this is probably not secure (i.e. mounting your home directory into the container) as in theory someone could steal your keys with a malicious container. 

The OS compatibility rules out mounting the node install folder. I looked at installing the slurm client, but put that into the too hard basket, and sort of an annoying additional step.

**Comment by pbranson** [comment]
> Pawsey users are no longer able to write to the volatile /run folder on the compute nodes. This prevented starting of jupyter which tries to write files there.

Regarding this turns out the fix is simple...

`export XDG_RUNTIME_DIR=""`
