### ISSUE TITLE
pangeo AWS account breach

### ISSUE THREAD

**Issue by robfatland** [pangeo-data/pangeo#675]
We had some minor Circle CI snafu in early July 2019. As a result AWS triggered an "account breach" and the account was flagged / disabled. AWS requests we rotate access keys prior to going back into business. Best as I can tell this means deleting old keys and generating new ones; then substituting the new ones so that the services that depend on the keys continue to work. I am checking in with some of you pangeo AWS account users to verify this is necessary. You can rotate your keys (delete + regenerate + re-assign) yourself or you can wait until I blow them away: You can still log in and under IAM / Users go to your security tab and generate a new key. If it comes to me deleting your old key(s) I will send you an email. On the far side AWS will re-enable the account and we can carry on normally. Apologies for any inconvenience.

**Comment by scottyhq** [comment]
Just noting here that this was due to exposing our AWS keys for our 'circleci` iam user by pushing unencrypyted keys to github on https://github.com/pangeo-data/pangeo-cloud-federation. To try to avoid this in the future we added the following to the repo readme, but changing to something other than git-crypt might be warranted moving forward... see
https://github.com/pangeo-data/pangeo-cloud-federation/pull/306

**Add your deployment's secrets directory to .gitattributes. IMPORTANT: before pushing to GitHub ensure encryption with `git-crypt status | grep secrets`**
