### ISSUE TITLE
build_pangeo_bib.py failing on travis

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#706]
`build_pangeo_bib.py` is failing on travis with a `503 Server Error`. This is causing other documentation updates to fail to build. 

```python-traceback
$ python build_pangeo_bib.py
Traceback (most recent call last):
  File "build_pangeo_bib.py", line 15, in <module>
    r.raise_for_status()
  File "/home/travis/miniconda/envs/docs-environment/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://api.crossref.org/works/10.1126/sciadv.aav5014/transform/application/x-bibtex
```

If the cross ref api is going to be unreliable, I wonder if we can find a way to make this step optionally pass the CI build.

@rabernat - ideas?

**Comment by jhamman** [comment]
I see now you've already seen this in https://github.com/pangeo-data/pangeo/pull/705#issuecomment-526182496.

**Comment by rabernat** [comment]
Right. We should follow crossref's API ettiquite:
https://github.com/CrossRef/rest-api-doc#etiquette

The right way to do this would probably be to:
- keep a bib file in the repo
- read the bib file in the `build_pangeo_bib.py` script
- only request DOIs for articles that are not already in the bib file
- use some kind of reasonable retries logic for API requests
- add the info to the API call as requested by crossref (e.g. email, headers, etc.)
- merge the new items with the old ones

That is more work than I can put into this little hack any time soon. So as a workaround, I say let's just remove the script from CI, version the bib file, and run the script manually whenever we want to update the bibliography.


#705 is actually a different problem:
https://travis-ci.org/pangeo-data/pangeo/builds/578268815

Even if you get past the crossref step, you get
```
  File "/home/travis/miniconda/envs/docs-environment/lib/python3.6/site-packages/pybtex/errors.py", line 78, in report_error
    raise exception
pybtex.database.BibliographyDataError: repeated bibliograhpy entry: Busecke_2019
```

This looks like:
https://bitbucket.org/pybtex-devs/pybtex/issues/119/add-option-to-ignore-duplicate-entries
It can be fixed by
```python
import pybtex.errors
pybtex.errors.set_strict_mode(False)
```

**Comment by rabernat** [comment]
What if we use a cache?

https://www.thepythoncorner.com/2018/04/how-to-make-your-code-faster-by-using-a-cache-in-python
