### ISSUE TITLE
Add New Zealand hydrodynamic hindcast from the Moana Project to pangeo

### ISSUE THREAD

**Issue by rsoutelino** [pangeo-data/pangeo#763]
Hi All, 

The [Moana Project](https://www.moanaproject.org) has recently released an open-access regional hydrodynamic [hindcast](https://www.moanaproject.org/data) of New Zealand waters using ROMS. I'm interested in contributing to making this dataset available in the cloud as an extra option to the ones made available by the Moana Project. I'm currently working on creating a zarr archive in google cloud for the entire dataset to enable easier data access within our projects. While doing that I thought it could be something others could find useful, and Pangeo came to mind. 

Is hosting such dataset in the scope of Pangeo? And if yes, what is the recommended process for making it happen? I'm familiar with intake and hosting these types of data in google cloud, so I'm happy to help with anything to facilitate the process if there are interest and scope.  

Regards

@joaometocean - keeping you in the loop

**Comment by rabernat** [comment]
Hi @rsoutelino -- thanks for the inquiry! Your project sounds awesome!

Just a point of clarification...there is really no such thing as putting a dataset "in Pangeo." If your dataset is in zarr archive on google cloud (or any cloud), it is already accessible from Pangeo cloud-based jupyterhubs, binder, etc. The only step left would be to add a pointer to in in our catalog, in order to make it easier for people to discover: https://github.com/pangeo-data/pangeo-datastore.

If you are asking whether we can pay the bill to host the dataset in the cloud, that is a more difficult question. We would want to know:
- How big is the dataset?
- Is it updated regularly?
- Can the organization who generated it afford to pay for cloud hosting? (Moana project appears to be quite well resourced.)
- Have you already inquired about adding it to a [public datasets program](https://cloud.google.com/public-datasets)?

**Comment by rsoutelino** [comment]
Hi @rabernat thanks for the quick reply! 

Great, it looks like it would be pretty straightforward then. I'm close to finishing the upload and conversion to zarr. 

In terms of hosting expenses, answering to your questions. 

- ~ 5 Tb
- Not regularly. There will be newer versions coming up, but they are likely to supersede each other.
- It could be a possibility, I'll let @joaometocean weigh in on that.
- I've considered this, but just wanted to check with pangeo first. Given that adding to pangeo just a matter of having a public zarr archive, I'll explore this further now.
