### ISSUE TITLE
Will Pangeo Catalog add Hycom Reanalysis data?

### ISSUE THREAD

**Issue by LemingVan** [pangeo-data/pangeo#779]
As we all know, Hycom Reanalysis data is widely used and can provide initial and forced fields for numerical models, so will Pangeo Catalog add it?

**Comment by rabernat** [comment]
Hi @LemingVan. Hycom Reanalysis is an excellent product. Cloud storage costs $250 TB / year. Our existing awards from Google cloud are about to expire. If the Hycom community wanted to pay for the cost of hosting the data, we would gladly help on the technical side. Otherwise, in order to do such things, we need money.

We currently have a new EarthCube proposal pending that would make it possible. If you and your community think this would be beneficial to you, feel free to reach out the the NSF program officers for EarthCube and express support for our proposal: https://www.nsf.gov/funding/pgm_summ.jsp?pims_id=504780

**Comment by LemingVan** [comment]
Hi, @rabernat. Thanks for your reply, i will take a look at EarthCube.
