### ISSUE TITLE
Dynamic deployments on the job scheduler

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#8]
Currently I find that I can more easily get access to many nodes if I ask for them one at a time

```
$ qsub start-dask.sh      # only ask for one machine
$ qsub add-one-worker.sh  # ask for one more machine
$ qsub add-one-worker.sh  # ask for one more machine
$ qsub add-one-worker.sh  # ask for one more machine
```

The workers find each other and connect up to form one logical job out of man independent ones.  This is fine from Dask's perspective but raises some potential questions from an IT / infrastructure perspective:

1.  Is this OK from an IT perspective (cc @davidedelvento)?  I would not be surprised to learn that I was abusing some policy that bumps up the priority of small jobs
2.  Is there some way that we should formalize this process?  For example, I'm also entirely willing to be bumped off of some of these machines if someone else comes by.  I can imagine specifying policies for this.

I suspect that this is beyond the scope of Cheyenne's existing job scheduler but it is something that we may want to consider long-term.  I thought I'd bring it up now.  This isn't any strong feature or service request.  This is just here for conversation.

**Comment by davidedelvento** [comment]
As far as Cheyenne's (and generally speaking NCAR's) policies go, this is totally fine, even encouraged (!) -- so go for it if it technically fits your needs.

The reason why small (and short, FWIW) jobs  are encouraged is because [the scheduler problem](https://en.wikipedia.org/wiki/Scheduling_(computing)) (or equivalently the [knapsack problem](https://en.wikipedia.org/wiki/Knapsack_problem)) is more efficiently "solved" if there are a number of small jobs: if you have a bucket filled to the top with gravel, you can not add more gravel to it, but you can still pour a large amount of sand into it! The sand are the small and short jobs, which can easily fill the gaps in utilization of the machine. In fact they do not have higher priority, they are just easier to find places for.

However do note that when you submit 4 jobs like in your example, there is no guarantee on when they will start. The first may start now, the second may start in 12 hours, the third tomorrow and the fourth next month, with little (if any) time overlap between them. This can be unlikely, but you need to know that's possible. If you can adjust the logic of how additional workers are used, great. Conceptually easy: lots of work to do, let me try to add more workers, if they start great, if not, I still have the other workers I started earlier.... Practilcally: your call :-)

Moreover, depending on how these workers are communicating with the master (or with other workers, if necessary) this may or may not work, since CISL would like to enforce some kind of insulation between "unrelated" jobs. Have you actually tried it yet?

Last, but not least, this approach will work well on an unreliable machine (Cheyenne is not one of such, but still we can simulate...) if one of the jobs dies, the other ones continue. Most schedulers in HPC centers assume that if one node dies the whole job dies, so it's harder to design fail tolerance.

**Comment by mrocklin** [comment]
> Moreover, depending on how these workers are communicating with the master (or with other workers, if necessary) this may or may not work, since CISL would like to enforce some kind of insulation between "unrelated" jobs. Have you actually tried it yet?

Yes, this is how I've been running things recently.  It has been working like a charm.  I have been accepting whatever amount of workers I get (although so far they have all come through) and at times I've even increased on the fly.  

> Last, but not least, this approach will work well on an unreliable machine (Cheyenne is not one of such, but still we can simulate...) if one of the jobs dies, the other ones continue. Most schedulers in HPC centers assume that if one node dies the whole job dies, so it's harder to design fail tolerance.

Yeah, Dask (and most other data-science-y frameworks) were designed with failing machines in mind.  Machines can come and go without significantly upsetting the user's experience (except the main one, which would cause everything to halt).

Do you happen to have an intuition (or actual data) on how many single or partial machines are typically free?  As we hopefully get more use out of the work going on here I suspect that people will start filling in more and more sand.  I'm curious how far we can go before getting back up to the top of the bucket.

**Comment by davidedelvento** [comment]
Great to hear. This seems the best approach, at least at NCAR (other datacenters have different policies, some e.g. prefer larger "capability" jobs, and schedule them with higher priority)

On Cheyenne at the moment 20-30% of the about 4,000 nodes (machines) are idle. Historically we have an average of 4% and the reason why it's so high now is two fold: i) some users are stuck with a issue with one piece of software not being ready, so they can't run; ii) we still have Yellowstone which is non-negligible size so some other users are running there (it will go away at the end of the year).

I expect to 20-30% to slowly go down to 4% from now to about February. Yet, 4% of 4,032 is still more than 100 nodes, so it's many. The tricky point to be able to utilize them is the requested wallclock. A nodes may be idle now, but may be "known by PBS to be busy in 1.2 hours". You can use it for 1.1 hours. CISL has some utilities for you to know this info, but I think it'd better if you use PBS resources for that (if you want to go into that business). Or submit 10 minutes jobs and deal with the failures. Or try to lobby for a pre-emptible queue (which some centers do): a queue with no requested time, whose jobs may be killed any time the scheduler needs them for something "more important" (so to speak).

You can check on the web the current node utilization at https://www2.cisl.ucar.edu/user-support/cisl-resource-status

**Comment by mrocklin** [comment]
> I expect to 20-30% to slowly go down to 4% from now to about February. Yet, 4% of 4,032 is still more than 100 nodes, so it's many.

Those are good numbers to know.  Thanks!

> Or try to lobby for a pre-emptible queue (which some centers do): a queue with no requested time, whose jobs may be killed any time the scheduler needs them for something "more important" (so to speak).

To make sure I understand correctly these are not currently deployed for Cheyenne, but are potentially sensible requests.

**Comment by davidedelvento** [comment]
> Thanks!

You're very welcome

>> Or try to lobby for a pre-emptible queue (which some centers do): a queue with no requested time, whose jobs may be killed any time the scheduler needs them for something "more important" (so to speak).
>
> To make sure I understand correctly these are not currently deployed for Cheyenne, but are potentially sensible requests.

Correct. There is not any deployed pre-emptible queue at NCAR, however it has been sometimes discussed.

**Comment by jhamman** [comment]
I think this can be safely closed. Both because we came to a resolution here and because dask-jobqueue has formalized much of this approach.
