### ISSUE TITLE
Best practices for fixing doc

### ISSUE THREAD

**Issue by lhoupert** [pangeo-data/pangeo#804]
Hi! 
Just a quick question about the best practices for propose edits on the documentation. I realised that editing online the .rst file created automatically some pull requests. Is it the way to go, or you would rather that is done through opening issues?

**Comment by jbusecke** [comment]
I personally think that is absolutely fine. I'd make a distinction between something small (like a typo etc), for which i'd just do a PR. 
A case when an issue might be appropriate could be when there is something more substantial up for debate, since issues are generally more visible to everyone?

Just my two cents.
