### ISSUE TITLE
Website refresh

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#922]
The Pangeo website (pangeo.io) is in desperate need of a refresh. Many pages are out of date or reflect a part of pangeo that has moved on to other spaces.

### What needs to be updated?
- governance and sponsorship policy, numfocus fiscal sponsorship (https://pangeo.io/about.html#governance)
- documentation of the technical parts of pangeo. Everything from packages, to cloud deployment guides
- https://pangeo.io/cloud.html
  - The 2i2c hubs are winding down so it would be good if we had some pointers for folks to help them understand what kind of options and services they could use to achieve pangeo-like cloud deployments. It would be nice if this included everything from DIY to managed solutions.
  - It would also be good to think of cloud as more than a Jupyterhub environment. We should include "compute" and "data" here, explaining how Pangeo enables cloud native science.
- https://pangeo.io/publications.html (perhaps this should move to the discourse forum)
- https://pangeo.io/contact.html
  - This page needs to explicitly state how to contact pangeo for various cases including sponsorship inquires, security issues, or code of conduct violations. 

### What should be removed?
- reference to outdated pages
  - https://pangeo.io/gallery.html
  - https://pangeo.io/meetings/index.html 
  - https://pangeo.io/data.html
    - This is very GCS specific and should probably just be rolled into the "cloud" page above.
- https://pangeo.io/collaborators.html
  - This was always poorly defined. I suggest we remove this. 
   
### What needs to be added?
- sponsors (similar to https://pangeo.io/collaborators.html targeted at specific sponsors)

----

There is obviously a lot to do here. It doesn't have to all be done by one person at once. I know @mrocklin had some ideas for how to structure some of the messaging around Pangeo's cloud documentation. @paigem and @AimeeB also started work on some of the home page messaging (#878). I suggest we use this issue to do a bit of coordination and move forward with some PRs to update the site over the coming weeks.

**Comment by mrocklin** [comment]
Thanks for bringing this up @jhamman .  For context for others I wrote up a similar doc with thoughts and shared it with a few folks. There's both thoughts on content there, but also thoughts on messaging and tone that I think would be helpful.

Doc here: https://docs.google.com/document/d/1Z-ndaHQ9IQR1lwNTZLsBo3uZQAiLMoTLedt9SvFGRjk/edit?usp=sharing

I'm happy to do some of this work, but I'm not sure how things happen with Pangeo these days.  In early days I would just change things.  I'm feeling less certain about agency though today.

**Comment by maxrjones** [comment]
In addition to a lot of the website's contents being out of date, this repository is also unlicensed and would be difficult to re-license at this point due to the large number of contributors. I would like to propose that we start afresh with a new website and gradually add pages necessary based on the currently relevant information from the new website.

**Proposed website start** (forked from xarray.dev): https://github.com/maxrjones/pangeo.io
**Deployed proposed website**: https://pangeo-io-git-main-max-jones-projects.vercel.app/
**Proposed timeline**:
September 9 - Max fills out the rest of the meeting / showcase pages
September 9 - 18: Solicit feedback on framework, decide whether to move forward with a new website
September 18 - October 8: adjust high-level plan for the website content based on steering council meetings, update sponsorship page
(if we decide to move forward with the new website)
October 8: migrate https://github.com/maxrjones/pangeo.io to pangeo-data github oganization
October 8 - October 31: add new pages as neededwith at least one week for review on each page
October 31: Deploy at pangeo.io, publish a blog post announcement

cc @jhamman @mrocklin @abarciauskas-bgse @paigem @TomNicholas @eni-awowale

**Comment by mrocklin** [comment]
This seems great!

My sense is that it's already better than what's deployed today.  Personally I'd be in favor of the following timeline:

-  Today: deploy on pangeo.io
-  Future: do all of the other stuff Max said

I often frame these questions by asking "if we had this new version deployed today, would we accept a change that put us at the older version?"

**Comment by TomNicholas** [comment]
Incredible work @maxrjones ! It already looks great. 

+1 for moving to a new website. 

Also +1 for just deploying it ASAP, I think as soon as visitors can use it to navigate to upcoming meetings / showcases then it's good enough to ship.

I have ideas for content for additional pages, but I agree with Matt that it's already considerably better.

**Comment by rabernat** [comment]
Amazing work here @maxrjones! 🙌 

I agree with the comments above...no need to wait months to roll this out.

**Comment by maxrjones** [comment]
Thanks for the feedback! That works for me, I'll transfer it over and work on setting Pangeo up as an open source team on Vercel so we can get free deployments. If anyone knows who owns the Pangeo domain, please reach out so that I can work with them to update the configuration for the old and new repositories sometime this week 🙏

**Comment by rabernat** [comment]
DNS came up here - https://discourse.pangeo.io/t/pangeo-dns-outage-july-4-2024/4324 

Looks like it's me, @jhamman, and @TomAugspurger who have DNS access right now. Happy to share access with you too Max or anyone interested in helping administer the site.

**Comment by abarciauskas-bgse** [comment]
Awesome work @maxrjones new site looks great!

**Comment by eni-awowale** [comment]
Great work @maxrjones ! Another +1 for deploying it right away. I think it will be easier to collect feedback once people are actually using the site regularly.

**Comment by dcherian** [comment]
Executing at will! I like it, like it

**Comment by maxrjones** [comment]
Thanks for all the enthusiasm on this! Very grateful to be part of such a friendly community!

I transferred the repository to https://github.com/pangeo-data/pangeo.io and opened a bunch of issues that capture the other discussion points from this website refresh issue.

Since I labelled most of the issues as help-wanted, I'd like to create a `website-maintenance` team in the pangeo-data org comprised of people willing relatively promptly review/merge PRs in https://github.com/pangeo-data/pangeo.io. Please add an 👀  emoji to this comment if you'd like to serve on that team. Thank you!

**Comment by mrocklin** [comment]
Thanks for leading this Max!
