### ISSUE TITLE
Connections with Open Data Cube?

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#96]
Do we have any Pangeo members that are working with the Open Data Cube project: https://www.opendatacube.org/?

Looking through their repositories, it seems like they are building out a very similar xarray/dask stack, with a focus on remote sensing datasets. 

I will cross post on their main repository as well: https://github.com/opendatacube/datacube-core

**Comment by hot007** [comment]
I used to be associated... I'll ping one of their devs :)

**Comment by rabernat** [comment]
I exchanged emails with Brian Killough of NASA after ESIP. He is involved in open data cube via [CEOS](https://www.opendatacube.org/ceos) at some high level. He made some nice comments about our project and expressed a willingness to collaborate.

**Comment by andrewdhicks** [comment]
Hi @jhamman 
I'm one of the devs on Open Data Cube.  We are big fans of xarray and dask.

Open Data Cube is basically a database of datasets that can return an xarray, with a bunch of algorithms and applications that are built around xarray.
We have members from quite a few countries so we are keen to collaborate.  Making it easier to merge climate and remote sensing datasets would be great.

(Thanks @hot007 for the ping)

**Comment by mrocklin** [comment]
Thank you for chiming in @andrewdhicks .  I'm glad that you've been able to put XArray and Dask to some use.  I have two questions from a dask perspective:

1.  Have you tried things on a distributed cluster?  Do you have any reason to believe that this would be easier or harder than in vanilla XArray cases?
2.  What computational operations would you want to efficiently and intuitively merge datasets?

**Comment by jhamman** [comment]
xref on Open Data Cube github issues: https://github.com/opendatacube/datacube-core/issues/359

**Comment by andrewdhicks** [comment]
Hi @mrocklin
We tried to use distributed in its early days on HPC, but we found that it was too easy to trip the memory quota limits are have the job killed. Instead of dask.array, we have using distributed as a futures backend to run jobs hand-crafted to known memory limits across multiple workers.  The job then uses vanilla xarray, but it is a pain to do this hand-crafting to a memory footprint for every algorithm, so I expect dask arrays to make life easier.
With the new features in distributed to set memory limits and spill to disk, I'm really excited to try distributed again.  I just need to do a little bit more work to get it running with the right memory settings on our PBS Pro cluster.

There are a couple of main operations we do:
 * band ratios: e.g compare the red and near-infrared bands to get a normalized difference vegetation index (NDVI), which dask is really good at handling: `ndvi = (nir - red) / (nir + red)`
* unmixing algorithms: we have some Fortran code that transforms a 6-band array into a 60-term intermediate to run a non negative least squares operation against a set of endmembers to spit out a 4-term result. I'd like to try it out with `dask.array.apply_*` and see how it goes
* percentiles and higher-order medians over time: I think with a bit of 'rechunk'ing, we should be able to get some good results.  Use dask to read parallelise the reading of many spatial data files, then rechunk to get temporal stack that will fit into memory to do the medians.

As for merging datasets, a lot of it involves datasets of different spatial and temporal resolutions and doing interpolation between them. I'm not too involved in that side of things at the moment. There's generally some projection warping to get everything aligned first, so the first step is getting the `rasterio` reads working efficiently in the dask graph.

**Comment by guillaumeeb** [comment]
Hi all,
We tried Open Data Cube with Dask distributed on our PBS Pro based cluster at CNES in the end of last year with some success and lessons:
* Distributed ingestion into the Data Cube format was really easy,
* We had some memory problems with our Dask workers, but it was probably due to a lack of knowledge of Dask, now I think we are fine.
* We have some difficulties into knowing when to use Data Cube API, or when and how to use Dask/Xarray ones, but again this is probably a lack of mastering of these technologies.
* We are know in phase of looking for more precise experimental use cases and operations that could leverage the distributed nature of Dask/Xarray and ODC.

At the beginning we wanted to develop Spark workloads with Open Data Cube, but when we found it was all based on Dask and XArray, we just decided to use those.

Open Data Cube is really promising for us as a distributed multi dimentional data store for image analysis. As all of you have already observed, NetCDF and distributed storage and computing is still an open question, so we are trying to see if ODC can be an answer.

@andrewdhicks there are new resources for running Dask on PBSPro: a huge work from @mrocklin on pangeo (with dask-mpi), and we also worked on a simple PBS script available [here](https://github.com/guillaumeeb/big-data-frameworks-on-pbs).

**Comment by mrocklin** [comment]
These docs may also be of use to people using Dask on HPC systems.  It goes
through a number of lessons that we learned more generally:
http://dask.pydata.org/en/latest/setup/hpc.html

**Comment by guillaumeeb** [comment]
And I just see now the work you've done here on this pangeo repo with the Python wrapper to launch Dask on PBS! With adaptable capacity!
I will try to follow this more closely. Don't hesitate to keep me in touch on Dask and PBS!

**Comment by rsignell-usgs** [comment]
Following the [discussion of ODC on this week's Pangeo call](https://docs.google.com/document/d/1BkL0arf1Lz6fHgVBEJNxKbFmVN8glNQXmDKdsuT0GcU/edit#heading=h.6bg6n1yxu8hd), @jmunroe reached out to Robert Woodcock @woodcockr at CSIRO, and I looped in Alex Leith @alexgleith at Geoscience Australia, who also recently wrote a [nice blog post on recent ODC developments](https://medium.com/opendatacube/the-odc-retrospective-for-2018-d1a03c1cc9ae). 

They have COG data on S3, and JupyterHub running on Kubernetes with Dask (I believe).   So it seems there is a lot of opportunity for increasing connections between our communities.   Both Robert and Alex would be willing to meet with us on our weekly Pangeo check-in, which we suggested they do after Ryan returns. 

Robert also said this: 

> I’d also like to know if a representative from Pangeo might be willing to present at the next (long title coming) Committee on Earth Observation Satellites, Working Group on Information Systems and Services meeting (WGISS - Hanoi in October)? I’m the vice chair of WGISS and we are working towards updating the manner in which EO data is provided by major satellite data providers (USGS included). This is referred to as the Future Data Architecture initiative in CEOS and involves everything from Data discovery and supply, through to links into Cloud providers and analytical capabilities (of which ODC is one example, but not the only datacube technology). I believe many folks would be interested in the Pangeo ecosystem, intake and the complementary nature to the various data cube initiatives underway.
> 
> At a very practical level, I’d be interested if anyone in Pangeo knows why I’m getting assertion failures in dask distributed when running on an adaptive k8s cluster? The result appears correct but dask is complaining. I’m guessing the worker pods were killed before full clean up. I’m not alone with error judging by the issues on github. Low level I know, so a tad off topic for this thread but who knows you may have hit it too. ;-)
> 
Clearly we should reopen this issue!

**Comment by alexgleith** [comment]
Definitely keen to come to a Pangeo meeting. I was inspired to attempt to use Dask with the ODC after using some of the Pangeo demos. I think that the two projects are very close to each other, and we're talking currently about redesigning some aspects of the ODC database structure, and I wonder if talking to Pangeo will provide some context for us to focus on there too.

**Comment by rsignell-usgs** [comment]
@alexgleith, I think it would be cool to take one of the data intensive ODC workflows, like the creation of the [average high-tide/low-tide composite](https://www.researchgate.net/figure/The-high-tide-composite-left-panel-and-low-tide-composite-right-panel-median-surface_fig12_316080947) 
![The-high-tide-composite-left-panel-and-low-tide-composite-right-panel-median-surface](https://user-images.githubusercontent.com/1872600/60094470-29ef4000-971a-11e9-85b2-9e67000d5530.png)
and see what that workflow looks like using just Dask/Xarray/Rasterio on Kubernetes and using Pyviz for interactive visualization).  

Is the data necessary for that calculation already in COG on S3?

cc @tonybutzer

**Comment by alexgleith** [comment]
Hey @rsignell-usgs, I was inspired by the Twitter thread that identified ships in Sentinel 1 data, and we (@caitlinadams and I) worked it into a notebook that uses Dask in a neat way, here: https://github.com/frontiersi/dea-sandbox-notebooks/blob/master/casestudy_shipping_dask.ipynb

I'll email you a link to our Sandbox where you can run it.

Regarding coastline extractions and high tide work, we have some Landsat data that can be used for it, and a notebook here: https://github.com/frontiersi/dea-sandbox-notebooks/blob/master/Coastal_erosion_monitoring.ipynb. This one doesn't use Dask... Geoscience Australia run this for all of Australia in their super computer, and it uses a different kind of distributed workflow.

Email incoming.

**Comment by rsignell-usgs** [comment]
@alexgleith, yes, I was able to access and run both of those notebooks on your JuptyterHub -- they are awesome.   The coastal erosion one is very closely aligned with our work at USGS in the Coastal and Marine Program, so I'll share it around!   

I had some trouble trying to find the bucket for the Landsat data `ls8_nbar_scene` being used, which I was interested in to see if we could hit that directly.    Could you please provide the URL?

**Comment by alexgleith** [comment]
Hey Folks, how do I find my way into one of the Pangeo calls?

**Comment by fmaussion** [comment]
> Hey Folks, how do I find my way into one of the Pangeo calls?

http://pangeo.io/meeting-notes.html#pangeo-weekly-meeting-notes 

I'll try to join for my first meeting next Wed as well

**Comment by woodcockr** [comment]
Hey folks, I'll endeavour to get along to the next "Late Week" meeting as that's at somewhat more reasonable hour in my timezone.

**Comment by alexgleith** [comment]
I think I'm with @woodcockr and I'll aim for the meeting next week, which is at 6 am local time. 2 am does not sound awesome!
